// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}': Operation<
    '/solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}',
    'delete'
  >;
  /**
   * The list of drive inclusion rules applied to the tenant.
   */
  'GET /solutions/backupRestore/driveInclusionRules': Operation<
    '/solutions/backupRestore/driveInclusionRules',
    'get'
  >;
  /**
   * The list of drive inclusion rules applied to the tenant.
   */
  'GET /solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}': Operation<
    '/solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}': Operation<
    '/solutions/backupRestore/driveInclusionRules/{driveProtectionRule-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/driveInclusionRules': Operation<
    '/solutions/backupRestore/driveInclusionRules',
    'post'
  >;
}
