// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}': Operation<
    '/solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}',
    'delete'
  >;
  /**
   * The list of drive protection units in the tenant.
   */
  'GET /solutions/backupRestore/driveProtectionUnits': Operation<
    '/solutions/backupRestore/driveProtectionUnits',
    'get'
  >;
  /**
   * The list of drive protection units in the tenant.
   */
  'GET /solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}': Operation<
    '/solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}': Operation<
    '/solutions/backupRestore/driveProtectionUnits/{driveProtectionUnit-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/driveProtectionUnits': Operation<
    '/solutions/backupRestore/driveProtectionUnits',
    'post'
  >;
}
