// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Enable the Microsoft 365 Backup Storage service for a tenant.
   */
  'POST /solutions/backupRestore/enable': Operation<'/solutions/backupRestore/enable', 'post'>;
}
