// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Read the properties and relationships of a protectionUnitBase object.
   */
  'GET /solutions/backupRestore/protectionUnits': Operation<
    '/solutions/backupRestore/protectionUnits',
    'get'
  >;
  /**
   * Read the properties and relationships of a protectionUnitBase object.
   */
  'GET /solutions/backupRestore/protectionUnits/{protectionUnitBase-id}': Operation<
    '/solutions/backupRestore/protectionUnits/{protectionUnitBase-id}',
    'get'
  >;
}
