// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}': Operation<
    '/solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}',
    'delete'
  >;
  /**
   * The list of site inclusion rules applied to the tenant.
   */
  'GET /solutions/backupRestore/siteInclusionRules': Operation<
    '/solutions/backupRestore/siteInclusionRules',
    'get'
  >;
  /**
   * The list of site inclusion rules applied to the tenant.
   */
  'GET /solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}': Operation<
    '/solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}': Operation<
    '/solutions/backupRestore/siteInclusionRules/{siteProtectionRule-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/siteInclusionRules': Operation<
    '/solutions/backupRestore/siteInclusionRules',
    'post'
  >;
}
