// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}',
    'delete'
  >;
  /**
   * The list of site protection units in the tenant.
   */
  'GET /solutions/backupRestore/siteProtectionUnits': Operation<
    '/solutions/backupRestore/siteProtectionUnits',
    'get'
  >;
  /**
   * The list of site protection units in the tenant.
   */
  'GET /solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnits/{siteProtectionUnit-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/siteProtectionUnits': Operation<
    '/solutions/backupRestore/siteProtectionUnits',
    'post'
  >;
}
