// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration',
    'delete'
  >;
  /**
   * Read the properties and relationships of a virtualEventWebinarRegistrationConfiguration object.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration',
    'get'
  >;
  /**
   */
  'PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration',
    'patch'
  >;
}
