// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a member from a standard tag in a team.
   */
  'DELETE /teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}': Operation<
    '/teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}',
    'delete'
  >;
  /**
   * Get a list of the members of a standard tag in a team and their properties.
   */
  'GET /teams/{team-id}/tags/{teamworkTag-id}/members': Operation<
    '/teams/{team-id}/tags/{teamworkTag-id}/members',
    'get'
  >;
  /**
   * Get the properties and relationships of a member of a standard tag in a team.
   */
  'GET /teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}': Operation<
    '/teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}': Operation<
    '/teams/{team-id}/tags/{teamworkTag-id}/members/{teamworkTagMember-id}',
    'patch'
  >;
  /**
   * Create a new teamworkTagMember object in a team.
   */
  'POST /teams/{team-id}/tags/{teamworkTag-id}/members': Operation<
    '/teams/{team-id}/tags/{teamworkTag-id}/members',
    'post'
  >;
}
