// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /communications/callRecords/$count': Operation<'/communications/callRecords/$count', 'get'>;
}
