// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/callRecords/{callRecord-id}': Operation<
    '/communications/callRecords/{callRecord-id}',
    'delete'
  >;
  /**
   * Get the list of callRecord objects and their properties. The results can be optionally filtered using the $filter query parameter on the startDateTime and participant id properties. Note that the listed call records don&#x27;t include expandable relationships such as sessions and participants_v2. You can expand these relationships using Get callRecord for a specific record.
   */
  'GET /communications/callRecords': Operation<'/communications/callRecords', 'get'>;
  /**
   * Retrieve the properties and relationships of a callRecord object. You can get the id of a callRecord in two ways:
   * Subscribe to change notifications to the /communications/callRecords endpoint.
   * Use the callChainId property of a call. The call record is available only after the associated call is completed.
   */
  'GET /communications/callRecords/{callRecord-id}': Operation<
    '/communications/callRecords/{callRecord-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/callRecords/{callRecord-id}': Operation<
    '/communications/callRecords/{callRecord-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/callRecords': Operation<'/communications/callRecords', 'post'>;
}
