// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "DELETE /communications/callRecords/{callRecord-id}/organizer_v2": Operation<
    "/communications/callRecords/{callRecord-id}/organizer_v2",
    "delete"
  >;
  /**
   * Identity of the organizer of the call. This relationship is expanded by default in callRecord methods.
   */
  "GET /communications/callRecords/{callRecord-id}/organizer_v2": Operation<
    "/communications/callRecords/{callRecord-id}/organizer_v2",
    "get"
  >;
  /**
   */
  "PATCH /communications/callRecords/{callRecord-id}/organizer_v2": Operation<
    "/communications/callRecords/{callRecord-id}/organizer_v2",
    "patch"
  >;
}
