// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/bookingCurrencies/{bookingCurrency-id}': Operation<
    '/solutions/bookingCurrencies/{bookingCurrency-id}',
    'delete'
  >;
  /**
   * Get a list of bookingCurrency objects available to a Microsoft Bookings business.
   */
  'GET /solutions/bookingCurrencies': Operation<'/solutions/bookingCurrencies', 'get'>;
  /**
   * Get the properties of a bookingCurrency object that is available to a Microsoft Bookings business. Use the id property, which is the currency code, to specify the currency.
   */
  'GET /solutions/bookingCurrencies/{bookingCurrency-id}': Operation<
    '/solutions/bookingCurrencies/{bookingCurrency-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/bookingCurrencies/{bookingCurrency-id}': Operation<
    '/solutions/bookingCurrencies/{bookingCurrency-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/bookingCurrencies': Operation<'/solutions/bookingCurrencies', 'post'>;
}
