// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions': Operation<'/solutions', 'get'>;
  /**
   */
  'PATCH /solutions': Operation<'/solutions', 'patch'>;
}
