// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendarGroups/$count': Operation<'/me/calendarGroups/$count', 'get'>;
}
