// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a calendar group other than the default calendar group.
   */
  'DELETE /me/calendarGroups/{calendarGroup-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}',
    'delete'
  >;
  /**
   * Get the user&#x27;s calendar groups.
   */
  'GET /me/calendarGroups': Operation<'/me/calendarGroups', 'get'>;
  /**
   * Retrieve the properties and relationships of a calendar group object.
   */
  'GET /me/calendarGroups/{calendarGroup-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}',
    'get'
  >;
  /**
   * Update the properties of calendargroup object.
   */
  'PATCH /me/calendarGroups/{calendarGroup-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}',
    'patch'
  >;
  /**
   * Use this API to create a new CalendarGroup.
   */
  'POST /me/calendarGroups': Operation<'/me/calendarGroups', 'post'>;
}
