// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "POST /chats/{chat-id}/messages/{chatMessage-id}/setReaction": Operation<
    "/chats/{chat-id}/messages/{chatMessage-id}/setReaction",
    "post"
  >;
}
