// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /chats/{chat-id}/messages/{chatMessage-id}/unsetReaction': Operation<
    '/chats/{chat-id}/messages/{chatMessage-id}/unsetReaction',
    'post'
  >;
}
