// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions/backupRestore/driveProtectionUnits/$count': Operation<
    '/solutions/backupRestore/driveProtectionUnits/$count',
    'get'
  >;
}
