// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/restorePoints/{restorePoint-id}': Operation<
    '/solutions/backupRestore/restorePoints/{restorePoint-id}',
    'delete'
  >;
  /**
   * List of restore points in the tenant.
   */
  'GET /solutions/backupRestore/restorePoints': Operation<
    '/solutions/backupRestore/restorePoints',
    'get'
  >;
  /**
   * List of restore points in the tenant.
   */
  'GET /solutions/backupRestore/restorePoints/{restorePoint-id}': Operation<
    '/solutions/backupRestore/restorePoints/{restorePoint-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/restorePoints/{restorePoint-id}': Operation<
    '/solutions/backupRestore/restorePoints/{restorePoint-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/restorePoints': Operation<
    '/solutions/backupRestore/restorePoints',
    'post'
  >;
}
