// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Search for the restorePoint objects associated with a protectionUnit.
   */
  'POST /solutions/backupRestore/restorePoints/search': Operation<
    '/solutions/backupRestore/restorePoints/search',
    'post'
  >;
}
