// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Retrieve the chat of the specified user and Teams app.
   */
  'GET /users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}/chat': Operation<
    '/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}/chat',
    'get'
  >;
}
