// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Uninstall an app from the personal scope of the specified user.
   */
  'DELETE /users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}': Operation<
    '/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}',
    'delete'
  >;
  /**
   * Retrieve the list of apps installed in the personal scope of the specified user.
   */
  'GET /users/{user-id}/teamwork/installedApps': Operation<
    '/users/{user-id}/teamwork/installedApps',
    'get'
  >;
  /**
   * Retrieve the app installed in the personal scope of the specified user.
   */
  'GET /users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}': Operation<
    '/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}': Operation<
    '/users/{user-id}/teamwork/installedApps/{userScopeTeamsAppInstallation-id}',
    'patch'
  >;
  /**
   * Install an app in the personal scope of the specified user.
   */
  'POST /users/{user-id}/teamwork/installedApps': Operation<
    '/users/{user-id}/teamwork/installedApps',
    'post'
  >;
}
