// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'delete'
  >;
  /**
   * Retrieve the list of callTranscript objects associated with a scheduled onlineMeeting. This API doesn&#x27;t support getting call transcripts from channel meetings.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts',
    'get'
  >;
  /**
   * Retrieve a callTranscript object associated with a scheduled onlineMeeting. This API doesn&#x27;t support getting call transcripts from channel meetings. Retrieving the transcript returns the metadata of the single transcript associated with the online meeting. Retrieving the content of the transcript returns the stream of text associated with the transcript.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'patch'
  >;
  /**
   */
  'POST /users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/transcripts',
    'post'
  >;
}
