// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/backupRestore/protectionUnits/$count": Operation<
    "/solutions/backupRestore/protectionUnits/$count",
    "get"
  >;
}
