// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'GET /appCatalogs': Operation<'/appCatalogs', 'get'>;
  /**
   */
  'PATCH /appCatalogs': Operation<'/appCatalogs', 'patch'>;
}
