// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Accept the specified event in a user calendar.
   */
  'POST /me/calendarView/{event-id}/instances/{event-id1}/accept': Operation<
    '/me/calendarView/{event-id}/instances/{event-id1}/accept',
    'post'
  >;
}
