// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Hide a chat for a user.
   */
  'POST /me/chats/{chat-id}/hideForUser': Operation<'/me/chats/{chat-id}/hideForUser', 'post'>;
}
