// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/lastMessagePreview': Operation<
    '/me/chats/{chat-id}/lastMessagePreview',
    'delete'
  >;
  /**
   * Preview of the last message sent in the chat. Null if no messages were sent in the chat. Currently, only the list chats operation supports this property.
   */
  'GET /me/chats/{chat-id}/lastMessagePreview': Operation<
    '/me/chats/{chat-id}/lastMessagePreview',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/lastMessagePreview': Operation<
    '/me/chats/{chat-id}/lastMessagePreview',
    'patch'
  >;
}
