// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Mark a chat as read for a user.
   */
  'POST /me/chats/{chat-id}/markChatReadForUser': Operation<
    '/me/chats/{chat-id}/markChatReadForUser',
    'post'
  >;
}
