// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Mark a chat as unread for a user.
   */
  'POST /me/chats/{chat-id}/markChatUnreadForUser': Operation<
    '/me/chats/{chat-id}/markChatUnreadForUser',
    'post'
  >;
}
