// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'delete'
  >;
  /**
   * A collection of permissions granted to apps for the chat.
   */
  'GET /me/chats/{chat-id}/permissionGrants': Operation<
    '/me/chats/{chat-id}/permissionGrants',
    'get'
  >;
  /**
   * A collection of permissions granted to apps for the chat.
   */
  'GET /me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/me/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/permissionGrants': Operation<
    '/me/chats/{chat-id}/permissionGrants',
    'post'
  >;
}
