// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Send an activity feed notification in scope of a chat. For more information about sending notifications and the requirements for doing so, see sending Teams activity notifications.
   */
  'POST /me/chats/{chat-id}/sendActivityNotification': Operation<
    '/me/chats/{chat-id}/sendActivityNotification',
    'post'
  >;
}
