// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Unhide a chat for a user.
   */
  'POST /me/chats/{chat-id}/unhideForUser': Operation<'/me/chats/{chat-id}/unhideForUser', 'post'>;
}
