// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Activate a protectionPolicyBase. Currently, only one active backup policy per underlying service is supported (that is, one for OneDrive accounts, one for SharePoint sites, and one for Exchange Online users). You can add or remove artifacts (sites or user accounts) to or from each active policy.
   */
  'POST /solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}/activate': Operation<
    '/solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}/activate',
    'post'
  >;
}
