// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Deactivate a protectionPolicyBase.
   */
  'POST /solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}/deactivate': Operation<
    '/solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}/deactivate',
    'post'
  >;
}
