// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a protection policy. Read the properties and relationships of a protectionPolicyBase object.
   */
  'DELETE /solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}': Operation<
    '/solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}',
    'delete'
  >;
  /**
   * List of protection policies in the tenant.
   */
  'GET /solutions/backupRestore/protectionPolicies': Operation<
    '/solutions/backupRestore/protectionPolicies',
    'get'
  >;
  /**
   * List of protection policies in the tenant.
   */
  'GET /solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}': Operation<
    '/solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}': Operation<
    '/solutions/backupRestore/protectionPolicies/{protectionPolicyBase-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/protectionPolicies': Operation<
    '/solutions/backupRestore/protectionPolicies',
    'post'
  >;
}
