// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count',
    'get'
  >;
}
