// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'delete'
  >;
  /**
   * List all the replies to a message in a channel of a team. This method lists only the replies of the specified message, if any. To get the message itself, call get channel message.
   */
  'GET /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies',
    'get'
  >;
  /**
   * Retrieve a single message or a message reply in a channel or a chat.
   */
  'GET /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'patch'
  >;
  /**
   * Send a new reply to a chatMessage in a specified channel.
   */
  'POST /teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies': Operation<
    '/teams/{team-id}/channels/{channel-id}/messages/{chatMessage-id}/replies',
    'post'
  >;
}
