// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'delete'
  >;
  /**
   * Replies for a specified message. Supports $expand for channel messages.
   */
  'GET /me/chats/{chat-id}/messages/{chatMessage-id}/replies': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies',
    'get'
  >;
  /**
   * Replies for a specified message. Supports $expand for channel messages.
   */
  'GET /me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/messages/{chatMessage-id}/replies': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies',
    'post'
  >;
}
