// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}',
    'delete'
  >;
  /**
   * Get the list of all virtualEventWebinar objects created in a tenant.
   */
  'GET /solutions/virtualEvents/webinars': Operation<'/solutions/virtualEvents/webinars', 'get'>;
  /**
   * Read the properties and relationships of a virtualEventWebinar object. All roles can get the details of a webinar event.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}',
    'get'
  >;
  /**
   * Update the properties of a virtualEventWebinar object. Only the Organizer and Co-organizer can make changes to a webinar event.
   */
  'PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}',
    'patch'
  >;
  /**
   * Create a new virtualEventWebinar object in draft mode.
   */
  'POST /solutions/virtualEvents/webinars': Operation<'/solutions/virtualEvents/webinars', 'post'>;
}
