// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}',
    'delete'
  >;
  /**
   * The virtual event presenters.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters',
    'get'
  >;
  /**
   * The virtual event presenters.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}',
    'get'
  >;
  /**
   * Update the properties of a virtualEventPresenter object. Currently the supported virtual event types are:
- virtualEventWebinar.
   */
  'PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters/{virtualEventPresenter-id}',
    'patch'
  >;
  /**
   * Create a new virtualEventPresenter object on a virtual event. Currently, the following types of virtual events are supported: 
- virtualEventTownhall
- virtualEventWebinar
   */
  'POST /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/presenters',
    'post'
  >;
}
