// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}/learningContents/$count': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents/$count',
    'get'
  >;
}
