// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/calls/{call-id}/operations/$count": Operation<
    "/communications/calls/{call-id}/operations/$count",
    "get"
  >;
}
