// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendar/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendar/calendarPermissions/{calendarPermission-id}',
    'delete'
  >;
  /**
   * The permissions of the users with whom the calendar is shared.
   */
  'GET /me/calendar/calendarPermissions': Operation<'/me/calendar/calendarPermissions', 'get'>;
  /**
   * The permissions of the users with whom the calendar is shared.
   */
  'GET /me/calendar/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendar/calendarPermissions/{calendarPermission-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendar/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendar/calendarPermissions/{calendarPermission-id}',
    'patch'
  >;
  /**
   * Create a calendarPermission resource to specify the identity and role of the user with whom the specified calendar is being shared or delegated.
   */
  'POST /me/calendar/calendarPermissions': Operation<'/me/calendar/calendarPermissions', 'post'>;
}
