// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /teamwork/deletedTeams/getAllMessages()': Operation<
    '/teamwork/deletedTeams/getAllMessages()',
    'get'
  >;
}
