// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teamwork/deletedTeams/{deletedTeam-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}',
    'delete'
  >;
  /**
   * Get a list of the deletedTeam objects and their properties.
   */
  'GET /teamwork/deletedTeams': Operation<'/teamwork/deletedTeams', 'get'>;
  /**
   * The deleted team.
   */
  'GET /teamwork/deletedTeams/{deletedTeam-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}',
    'get'
  >;
  /**
   */
  'PATCH /teamwork/deletedTeams/{deletedTeam-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}',
    'patch'
  >;
  /**
   */
  'POST /teamwork/deletedTeams': Operation<'/teamwork/deletedTeams', 'post'>;
}
