// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Adds a strong password or secret to an application. You can also add passwords while creating the application.
   */
  'POST /applications/{application-id}/addPassword': Operation<
    '/applications/{application-id}/addPassword',
    'post'
  >;
}
