// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * The appManagementPolicy applied to this application.
   */
  'GET /applications/{application-id}/appManagementPolicies': Operation<
    '/applications/{application-id}/appManagementPolicies',
    'get'
  >;
}
