// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'POST /applications/{application-id}/checkMemberObjects': Operation<
    '/applications/{application-id}/checkMemberObjects',
    'post'
  >;
}
