// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Supports $filter (/$count eq 0, /$count ne 0). Read-only.
   */
  'GET /applications/{application-id}/createdOnBehalfOf': Operation<
    '/applications/{application-id}/createdOnBehalfOf',
    'get'
  >;
}
