// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'GET /applications/{application-id}/homeRealmDiscoveryPolicies': Operation<
    '/applications/{application-id}/homeRealmDiscoveryPolicies',
    'get'
  >;
  /**
   */
  'GET /applications/{application-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}': Operation<
    '/applications/{application-id}/homeRealmDiscoveryPolicies/{homeRealmDiscoveryPolicy-id}',
    'get'
  >;
}
