// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Delete an application object. When deleted, apps are moved to a temporary container and can be restored within 30 days. After that time, they are permanently deleted.
   */
  'DELETE /applications/{application-id}': Operation<'/applications/{application-id}', 'delete'>;
  /**
   * Get the list of applications in this organization.
   */
  'GET /applications': Operation<'/applications', 'get'>;
  /**
   * Get the properties and relationships of an application object.
   */
  'GET /applications/{application-id}': Operation<'/applications/{application-id}', 'get'>;
  /**
   * Create a new application object if it doesn&#x27;t exist, or update the properties of an existing application object.
   */
  'PATCH /applications/{application-id}': Operation<'/applications/{application-id}', 'patch'>;
  /**
   * Create a new application object.
   */
  'POST /applications': Operation<'/applications', 'post'>;
}
