// DO NOT EDIT THIS FILE
import type { Operation } from './../common.d.ts';

export interface Endpoints {
  /**
   * Delete an application object. When deleted, apps are moved to a temporary container and can be restored within 30 days. After that time, they are permanently deleted.
   */
  'DELETE /applications/{application-id}': Operation<'/applications/{application-id}', 'delete'>;
  /**
   * Delete a federatedIdentityCredential object from an application.
   */
  'DELETE /applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)': Operation<
    '/applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)',
    'delete'
  >;
  /**
   * Get the list of applications in this organization.
   */
  'GET /applications': Operation<'/applications', 'get'>;
  /**
   * Get the properties and relationships of an application object.
   */
  'GET /applications/{application-id}': Operation<'/applications/{application-id}', 'get'>;
  /**
   * Read the properties and relationships of a federatedIdentityCredential object.
   */
  'GET /applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)': Operation<
    '/applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)',
    'get'
  >;
  /**
   * Create a new application object if it doesn&#x27;t exist, or update the properties of an existing application object.
   */
  'PATCH /applications/{application-id}': Operation<'/applications/{application-id}', 'patch'>;
  /**
   * Create a new federatedIdentityCredential object for an application if it doesn&#x27;t exist, or update the properties of an existing federatedIdentityCredential object. By configuring a trust relationship between your Microsoft Entra application registration and the identity provider for your compute platform, you can use tokens issued by that platform to authenticate with Microsoft identity platform and call APIs in the Microsoft ecosystem. Maximum of 20 objects can be added to an application.
   */
  'PATCH /applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)': Operation<
    '/applications/{application-id}/federatedIdentityCredentials(name&#x3D;&#x27;{name}&#x27;)',
    'patch'
  >;
  /**
   * Create a new application object.
   */
  'POST /applications': Operation<'/applications', 'post'>;
}
