// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Retrieve a list of owners for an application that are directoryObject types.
   */
  'GET /applications/{application-id}/owners': Operation<
    '/applications/{application-id}/owners',
    'get'
  >;
}
