// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Remove a key credential from an application. This method along with addKey can be used by an application to automate rolling its expiring keys. As part of the request validation for this method, a proof of possession of an existing key is verified before the action can be performed.
   */
  'POST /applications/{application-id}/removeKey': Operation<
    '/applications/{application-id}/removeKey',
    'post'
  >;
}
