// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Remove a password from an application.
   */
  'POST /applications/{application-id}/removePassword': Operation<
    '/applications/{application-id}/removePassword',
    'post'
  >;
}
