// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * List the tokenIssuancePolicy objects that are assigned to an application.
   */
  'GET /applications/{application-id}/tokenIssuancePolicies': Operation<
    '/applications/{application-id}/tokenIssuancePolicies',
    'get'
  >;
}
