// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * List the tokenLifetimePolicy objects that are assigned to an application. Only one object is returned in the collection because only one tokenLifetimePolicy can be assigned to an application.
   */
  'GET /applications/{application-id}/tokenLifetimePolicies': Operation<
    '/applications/{application-id}/tokenLifetimePolicies',
    'get'
  >;
}
