// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Unset the verifiedPublisher previously set on an application, removing all verified publisher properties. For more information, see Publisher verification.
   */
  'POST /applications/{application-id}/unsetVerifiedPublisher': Operation<
    '/applications/{application-id}/unsetVerifiedPublisher',
    'post'
  >;
}
