// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/$count': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/$count',
    'get'
  >;
}
