// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}',
    'delete'
  >;
  /**
   * Retrieve a list of calendars belonging to a calendar group.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars',
    'get'
  >;
  /**
   * The calendars in the calendar group. Navigation property. Read-only. Nullable.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}',
    'patch'
  >;
  /**
   * Use this API to create a new calendar in a calendar group for a user.
   */
  'POST /me/calendarGroups/{calendarGroup-id}/calendars': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars',
    'post'
  >;
}
