// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "DELETE /communications/callRecords/{callRecord-id}/participants_v2/{participant-id}": Operation<
    "/communications/callRecords/{callRecord-id}/participants_v2/{participant-id}",
    "delete"
  >;
  /**
   * Get the list of participant objects associated with a callRecord.
   */
  "GET /communications/callRecords/{callRecord-id}/participants_v2": Operation<
    "/communications/callRecords/{callRecord-id}/participants_v2",
    "get"
  >;
  /**
   * List of distinct participants in the call.
   */
  "GET /communications/callRecords/{callRecord-id}/participants_v2/{participant-id}": Operation<
    "/communications/callRecords/{callRecord-id}/participants_v2/{participant-id}",
    "get"
  >;
  /**
   */
  "PATCH /communications/callRecords/{callRecord-id}/participants_v2/{participant-id}": Operation<
    "/communications/callRecords/{callRecord-id}/participants_v2/{participant-id}",
    "patch"
  >;
  /**
   */
  "POST /communications/callRecords/{callRecord-id}/participants_v2": Operation<
    "/communications/callRecords/{callRecord-id}/participants_v2",
    "post"
  >;
}
