// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   * Determine whether a user has access to a shared channel.
   */
  'GET /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/doesUserHaveAccess(userId&#x3D;&#x27;@userId&#x27;,tenantId&#x3D;&#x27;@tenantId&#x27;,userPrincipalName&#x3D;&#x27;@userPrincipalName&#x27;)': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/doesUserHaveAccess(userId&#x3D;&#x27;@userId&#x27;,tenantId&#x3D;&#x27;@tenantId&#x27;,userPrincipalName&#x3D;&#x27;@userPrincipalName&#x27;)',
    'get'
  >;
}
