// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   * Retrieve messages across all channels in a team, including text, audio, and video conversations. To learn more about how to use the Microsoft Teams export APIs to export content, see Export content with the Microsoft Teams export APIs.
   */
  "GET /teamwork/deletedTeams/{deletedTeam-id}/channels/getAllMessages()": Operation<
    "/teamwork/deletedTeams/{deletedTeam-id}/channels/getAllMessages()",
    "get"
  >;
}
