// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}',
    'delete'
  >;
  /**
   * The channels that are either shared with this deleted team or created in this deleted team.
   */
  'GET /teamwork/deletedTeams/{deletedTeam-id}/channels': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels',
    'get'
  >;
  /**
   * The channels that are either shared with this deleted team or created in this deleted team.
   */
  'GET /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}',
    'get'
  >;
  /**
   */
  'PATCH /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}',
    'patch'
  >;
  /**
   */
  'POST /teamwork/deletedTeams/{deletedTeam-id}/channels': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels',
    'post'
  >;
}
