// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Provision an email address for a channel. Microsoft Teams doesn&#x27;t automatically provision an email address for a channel by default. To have Teams provision an email address, you can call provisionEmail, or through the Teams user interface, select Get email address, which triggers Teams to generate an email address if it has not already provisioned one. To remove the email address of a channel, use the removeEmail method.
   */
  'POST /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/provisionEmail': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/provisionEmail',
    'post'
  >;
}
