// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Remove the email address of a channel. You can remove an email address only if it was provisioned using the provisionEmail method or through the Microsoft Teams client.
   */
  'POST /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/removeEmail': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/removeEmail',
    'post'
  >;
}
