// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Restore an archived channel. Unarchiving restores the ability for users to send messages and edit the channel. Channels are archived via the channel: archive method. Unarchiving is an asynchronous operation; a channel is unarchived when the asynchronous unarchiving operation completes successfully, which might occur after this method responds.
   */
  'POST /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/unarchive': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/unarchive',
    'post'
  >;
}
