// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   * Remove a tokenLifetimePolicy from an application.
   */
  "DELETE /applications/{application-id}/tokenLifetimePolicies/$ref": Operation<
    "/applications/{application-id}/tokenLifetimePolicies/$ref",
    "delete"
  >;
  /**
   * Remove a tokenLifetimePolicy from an application.
   */
  "DELETE /applications/{application-id}/tokenLifetimePolicies/{tokenLifetimePolicy-id}/$ref": Operation<
    "/applications/{application-id}/tokenLifetimePolicies/{tokenLifetimePolicy-id}/$ref",
    "delete"
  >;
  /**
   * List the tokenLifetimePolicy objects that are assigned to an application. Only one object is returned in the collection because only one tokenLifetimePolicy can be assigned to an application.
   */
  "GET /applications/{application-id}/tokenLifetimePolicies/$ref": Operation<
    "/applications/{application-id}/tokenLifetimePolicies/$ref",
    "get"
  >;
  /**
   * Assign a tokenLifetimePolicy to an application. You can have multiple tokenLifetimePolicy policies in a tenant but can assign only one tokenLifetimePolicy per application.
   */
  "POST /applications/{application-id}/tokenLifetimePolicies/$ref": Operation<
    "/applications/{application-id}/tokenLifetimePolicies/$ref",
    "post"
  >;
}
