// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count": Operation<
    "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/extensions/$count",
    "get"
  >;
}
