// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/setReaction': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/setReaction',
    'post'
  >;
}
