// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Undo soft deletion of a single chatMessage or a chat message reply in a channel or a chat.
   */
  'POST /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/undoSoftDelete': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/undoSoftDelete',
    'post'
  >;
}
