// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Send activity feed notifications to multiple users, in bulk.  For more information, see sending Teams activity notifications.
   */
  'POST /teamwork/sendActivityNotificationToRecipients': Operation<
    '/teamwork/sendActivityNotificationToRecipients',
    'post'
  >;
}
