// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teamwork/teamsAppSettings': Operation<'/teamwork/teamsAppSettings', 'delete'>;
  /**
   * Get the tenant-wide teamsAppSettings for all Teams apps in the tenant.
   */
  'GET /teamwork/teamsAppSettings': Operation<'/teamwork/teamsAppSettings', 'get'>;
  /**
   * Update the tenant-wide teamsAppSettings for all Teams apps in the tenant.
   */
  'PATCH /teamwork/teamsAppSettings': Operation<'/teamwork/teamsAppSettings', 'patch'>;
}
