// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Delete an instance of a workforceIntegration.
   */
  'DELETE /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'delete'
  >;
  /**
   * Retrieve a list of workforceIntegration objects.
   */
  'GET /teamwork/workforceIntegrations': Operation<'/teamwork/workforceIntegrations', 'get'>;
  /**
   * Retrieve the properties and relationships of a workforceIntegration object.
   */
  'GET /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'get'
  >;
  /**
   * Update the properties of a workforceIntegration object.
   */
  'PATCH /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'patch'
  >;
  /**
   * Create a new workforceIntegration object.
You can set up which entities you want to receive Shifts synchronous change notifications on and set entities to configure filtering by WFM rules eligibility for, including swap requests.
   */
  'POST /teamwork/workforceIntegrations': Operation<'/teamwork/workforceIntegrations', 'post'>;
}
