// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}': Operation<
    '/solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}',
    'delete'
  >;
  /**
   * The list of Exchange restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/exchangeRestoreSessions': Operation<
    '/solutions/backupRestore/exchangeRestoreSessions',
    'get'
  >;
  /**
   * The list of Exchange restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}': Operation<
    '/solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}',
    'get'
  >;
  /**
   * Update the properties of an exchangeRestoreSession.
   */
  'PATCH /solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}': Operation<
    '/solutions/backupRestore/exchangeRestoreSessions/{exchangeRestoreSession-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/exchangeRestoreSessions': Operation<
    '/solutions/backupRestore/exchangeRestoreSessions',
    'post'
  >;
}
