// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Metadata for the location where the channel&#x27;s files are stored.
   */
  'GET /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/filesFolder': Operation<
    '/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/filesFolder',
    'get'
  >;
}
