// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /me/calendarView/$count": Operation<"/me/calendarView/$count", "get">;
}
