// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/sessions/$count": Operation<
    "/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/sessions/$count",
    "get"
  >;
}
