// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/$count": Operation<
    "/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/$count",
    "get"
  >;
}
