// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}': Operation<
    '/users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}',
    'delete'
  >;
  /**
   * The list of associatedTeamInfo objects that a user is associated with.
   */
  'GET /users/{user-id}/teamwork/associatedTeams': Operation<
    '/users/{user-id}/teamwork/associatedTeams',
    'get'
  >;
  /**
   * The list of associatedTeamInfo objects that a user is associated with.
   */
  'GET /users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}': Operation<
    '/users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}': Operation<
    '/users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}',
    'patch'
  >;
  /**
   */
  'POST /users/{user-id}/teamwork/associatedTeams': Operation<
    '/users/{user-id}/teamwork/associatedTeams',
    'post'
  >;
}
