// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'GET /users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}/team': Operation<
    '/users/{user-id}/teamwork/associatedTeams/{associatedTeamInfo-id}/team',
    'get'
  >;
}
