// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   * Get all retained messages across all channels in a team. To learn more about how to use the Microsoft Teams export APIs to export content, see Export content with the Microsoft Teams export APIs.
   */
  "GET /teams/{team-id}/channels/getAllRetainedMessages()": Operation<
    "/teams/{team-id}/channels/getAllRetainedMessages()",
    "get"
  >;
}
