// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /teams/{team-id}/incomingChannels/$count': Operation<
    '/teams/{team-id}/incomingChannels/$count',
    'get'
  >;
}
