// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration/questions/$count": Operation<
    "/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrationConfiguration/questions/$count",
    "get"
  >;
}
