// DO NOT EDIT THIS FILE
import type { Operation } from "./../common.d.ts";

export interface Endpoints {
  /**
   * Get the presence information for multiple users.
   */
  "POST /communications/getPresencesByUserId": Operation<
    "/communications/getPresencesByUserId",
    "post"
  >;
}
