// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'GET /communications': Operation<'/communications', 'get'>;
  /**
   */
  'PATCH /communications': Operation<'/communications', 'patch'>;
}
