// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/delta()": Operation<
    "/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/delta()",
    "get"
  >;
}
