// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'delete'
  >;
  /**
   * Get a callRecording object associated with a scheduled onlineMeeting. This API doesn&#x27;t support getting call recordings from channel meetings. For a recording, this API returns the metadata of the single recording associated with the online meeting. For the content of a recording, this API returns the stream of bytes associated with the recording.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings',
    'get'
  >;
  /**
   * Get a callRecording object associated with a scheduled onlineMeeting. This API doesn&#x27;t support getting call recordings from channel meetings. For a recording, this API returns the metadata of the single recording associated with the online meeting. For the content of a recording, this API returns the stream of bytes associated with the recording.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'patch'
  >;
  /**
   */
  'POST /users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/recordings',
    'post'
  >;
}
