// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Remove a conversationMember from a team.
   */
  'DELETE /teams/{team-id}/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/members/{conversationMember-id}',
    'delete'
  >;
  /**
   * Get the conversationMember collection of a team. The membership IDs returned by the server must be treated as opaque strings. The client shouldn&#x27;t try to parse or make assumptions about these resource IDs. In the future, membership results can include users from various tenants, as indicated in the response. Clients should avoid assuming that all members exclusively belong to the current tenant.
   */
  'GET /teams/{team-id}/members': Operation<'/teams/{team-id}/members', 'get'>;
  /**
   * Get a conversationMember from a team.
   */
  'GET /teams/{team-id}/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/members/{conversationMember-id}',
    'get'
  >;
  /**
   * Update the role of a conversationMember in a team.
   */
  'PATCH /teams/{team-id}/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/members/{conversationMember-id}',
    'patch'
  >;
  /**
   * Add a new conversationMember to a team.
   */
  'POST /teams/{team-id}/members': Operation<'/teams/{team-id}/members', 'post'>;
}
