// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /applications/{application-id}/owners/graph.endpoint/$count": Operation<
    "/applications/{application-id}/owners/graph.endpoint/$count",
    "get"
  >;
}
