// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /applications/{application-id}/owners/graph.endpoint': Operation<
    '/applications/{application-id}/owners/graph.endpoint',
    'get'
  >;
  /**
   */
  'GET /applications/{application-id}/owners/{directoryObject-id}/graph.endpoint': Operation<
    '/applications/{application-id}/owners/{directoryObject-id}/graph.endpoint',
    'get'
  >;
}
