// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /users/{user-id}/chats/{chat-id}/installedApps/$count': Operation<
    '/users/{user-id}/chats/{chat-id}/installedApps/$count',
    'get'
  >;
}
