// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /me/calendar/calendarView/{event-id}/attachments/$count": Operation<
    "/me/calendar/calendarView/{event-id}/attachments/$count",
    "get"
  >;
}
