// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * The content stream of the attendee report of a Microsoft Teams live event. Read-only.
   */
  'DELETE /users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport',
    'delete'
  >;
  /**
   * The content stream of the attendee report of a Microsoft Teams live event. Read-only.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport',
    'get'
  >;
  /**
   * The content stream of the attendee report of a Microsoft Teams live event. Read-only.
   */
  'PUT /users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/attendeeReport',
    'put'
  >;
}
