// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /users/{user-id}/onlineMeetings/$count': Operation<
    '/users/{user-id}/onlineMeetings/$count',
    'get'
  >;
}
