// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   * Get all recordings from scheduled onlineMeeting instances for which the specified user is the organizer. This API currently doesn&#x27;t support getting call recordings from channel meetings. You can apply the delta function on getAllRecordings to synchronize and get callRecording resources as they&#x27;re added for onlineMeeting instances organized by the specified user. The delta query supports both full synchronization and incremental synchronization. Full synchronization gets all the recordings for online meetings organized by the user. Incremental synchronization gets recordings that are added since the last synchronization. Typically, you perform an initial full synchronization, and then get incremental changes to that recording view periodically. Find more information in the delta query documentation. For more examples, see callRecording: delta. To learn more about using the Microsoft Teams export APIs to export content, see Export content with the Microsoft Teams export APIs.
   */
  "GET /users/{user-id}/onlineMeetings/getAllRecordings(meetingOrganizerUserId&#x3D;&#x27;@meetingOrganizerUserId&#x27;,startDateTime&#x3D;@startDateTime,endDateTime&#x3D;@endDateTime)": Operation<
    "/users/{user-id}/onlineMeetings/getAllRecordings(meetingOrganizerUserId&#x3D;&#x27;@meetingOrganizerUserId&#x27;,startDateTime&#x3D;@startDateTime,endDateTime&#x3D;@endDateTime)",
    "get"
  >;
}
