// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   * Get a join web URL for a Microsoft Virtual Appointment. This web URL includes enhanced business-to-customer experiences such as mobile browser join and virtual lobby rooms. With Teams Premium, you can configure a custom lobby room experience for attendees by adding your company logo and access the Virtual Appointments usage report for organizational analytics.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}/getVirtualAppointmentJoinWebUrl()': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}/getVirtualAppointmentJoinWebUrl()',
    'get'
  >;
}
