// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/onlineMeetings/{onlineMeeting-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}',
    'delete'
  >;
  /**
   * Information about a meeting, including the URL used to join a meeting, the attendees list, and the description.
   */
  'GET /users/{user-id}/onlineMeetings': Operation<'/users/{user-id}/onlineMeetings', 'get'>;
  /**
   * Information about a meeting, including the URL used to join a meeting, the attendees list, and the description.
   */
  'GET /users/{user-id}/onlineMeetings/{onlineMeeting-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/onlineMeetings/{onlineMeeting-id}': Operation<
    '/users/{user-id}/onlineMeetings/{onlineMeeting-id}',
    'patch'
  >;
  /**
   */
  'POST /users/{user-id}/onlineMeetings': Operation<'/users/{user-id}/onlineMeetings', 'post'>;
}
