// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   * Cancel a registrant&#x27;s registration record for a webinar.
   */
  'POST /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)/cancel': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)/cancel',
    'post'
  >;
}
