// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)',
    'delete'
  >;
  /**
   * Get the properties and relationships of a virtualEventRegistration object.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)',
    'get'
  >;
  /**
   */
  'PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(userId&#x3D;&#x27;{userId}&#x27;)',
    'patch'
  >;
}
