// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /applications/{application-id}/extensionProperties/$count": Operation<
    "/applications/{application-id}/extensionProperties/$count",
    "get"
  >;
}
