// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions/virtualEvents/townhalls/$count': Operation<
    '/solutions/virtualEvents/townhalls/$count',
    'get'
  >;
}
