// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}',
    'delete'
  >;
  /**
   * Read the properties and relationships of a virtualEventTownhall object. All roles can get the details of a townhall event.
   */
  'GET /solutions/virtualEvents/townhalls': Operation<'/solutions/virtualEvents/townhalls', 'get'>;
  /**
   * Read the properties and relationships of a virtualEventTownhall object. All roles can get the details of a townhall event.
   */
  'GET /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}',
    'get'
  >;
  /**
   * Update the properties of a virtualEventTownhall object. Only the Organizer and Co-organizer can make changes to a townhall event.
   */
  'PATCH /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}',
    'patch'
  >;
  /**
   * Create a new virtualEventTownhall object in draft mode.
   */
  'POST /solutions/virtualEvents/townhalls': Operation<
    '/solutions/virtualEvents/townhalls',
    'post'
  >;
}
