// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a virtualEventPresenter from a virtual event. Currently the supported virtual event types are:
- virtualEventTownhall
- virtualEventWebinar
   */
  'DELETE /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}',
    'delete'
  >;
  /**
   * Get the list of all virtualEventPresenter objects associated with a virtual event. Currently the supported virtual event types are:
- virtualEventTownhall
- virtualEventWebinar
   */
  'GET /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters',
    'get'
  >;
  /**
   * Read the properties and relationships of a virtualEventPresenter object. Currently the supported virtual event types are: 
- virtualEventTownhall
- virtualEventWebinar
   */
  'GET /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters/{virtualEventPresenter-id}',
    'patch'
  >;
  /**
   * Create a new virtualEventPresenter object on a virtual event. Currently, the following types of virtual events are supported: 
- virtualEventTownhall
- virtualEventWebinar
   */
  'POST /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/presenters',
    'post'
  >;
}
