// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)": Operation<
    "/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)",
    "delete"
  >;
  /**
   * Get the properties and relationships of a virtualEventRegistration object.
   */
  "GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)": Operation<
    "/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)",
    "get"
  >;
  /**
   */
  "PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)": Operation<
    "/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations(email&#x3D;&#x27;{email}&#x27;)",
    "patch"
  >;
}
