// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Activate a draft restoreSessionBase object. The following points apply to restoring a protection unit:
   */
  'POST /solutions/backupRestore/restoreSessions/{restoreSessionBase-id}/activate': Operation<
    '/solutions/backupRestore/restoreSessions/{restoreSessionBase-id}/activate',
    'post'
  >;
}
