// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/backupRestore/restoreSessions/$count": Operation<
    "/solutions/backupRestore/restoreSessions/$count",
    "get"
  >;
}
