// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a draft restoreSessionBase object.
   */
  'DELETE /solutions/backupRestore/restoreSessions/{restoreSessionBase-id}': Operation<
    '/solutions/backupRestore/restoreSessions/{restoreSessionBase-id}',
    'delete'
  >;
  /**
   * Get a list of restoreSession objects and their properties.
   */
  'GET /solutions/backupRestore/restoreSessions': Operation<
    '/solutions/backupRestore/restoreSessions',
    'get'
  >;
  /**
   * Get the properties of a restoreSession object by ID.
   */
  'GET /solutions/backupRestore/restoreSessions/{restoreSessionBase-id}': Operation<
    '/solutions/backupRestore/restoreSessions/{restoreSessionBase-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/restoreSessions/{restoreSessionBase-id}': Operation<
    '/solutions/backupRestore/restoreSessions/{restoreSessionBase-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/restoreSessions': Operation<
    '/solutions/backupRestore/restoreSessions',
    'post'
  >;
}
