// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * The calendar view for the calendar. Navigation property. Read-only.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView',
    'get'
  >;
  /**
   * The calendar view for the calendar. Navigation property. Read-only.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/calendarView/{event-id}',
    'get'
  >;
}
