// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}',
    'delete'
  >;
  /**
   * Get the collection of bookingAppointment objects for a bookingBusiness that occurs in the specified date range.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/calendarView': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/calendarView',
    'get'
  >;
  /**
   * The set of appointments of this business in a specified date range. Read-only. Nullable.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/calendarView/{bookingAppointment-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/calendarView': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/calendarView',
    'post'
  >;
}
