// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'delete'
  >;
  /**
   * A collection of all the apps in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/installedApps': Operation<'/me/chats/{chat-id}/installedApps', 'get'>;
  /**
   * A collection of all the apps in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/installedApps': Operation<'/me/chats/{chat-id}/installedApps', 'post'>;
}
