// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Upgrade an app installation within a chat.
   */
  'POST /me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/upgrade': Operation<
    '/me/chats/{chat-id}/installedApps/{teamsAppInstallation-id}/upgrade',
    'post'
  >;
}
