// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /solutions/virtualEvents/events/{virtualEvent-id}/cancel': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/cancel',
    'post'
  >;
}
