// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/virtualEvents/events/$count": Operation<
    "/solutions/virtualEvents/events/$count",
    "get"
  >;
}
