// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}',
    'delete'
  >;
  /**
   * The virtual event presenters.
   */
  'GET /solutions/virtualEvents/events/{virtualEvent-id}/presenters': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/presenters',
    'get'
  >;
  /**
   * The virtual event presenters.
   */
  'GET /solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/presenters/{virtualEventPresenter-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/virtualEvents/events/{virtualEvent-id}/presenters': Operation<
    '/solutions/virtualEvents/events/{virtualEvent-id}/presenters',
    'post'
  >;
}
