// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   * Remove an appManagementPolicy policy object from an application or service principal object. When you remove the appManagementPolicy, the application or service principal adopts the tenant-wide tenantAppManagementPolicy setting.
   */
  'DELETE /applications/{application-id}/appManagementPolicies/$ref': Operation<
    '/applications/{application-id}/appManagementPolicies/$ref',
    'delete'
  >;
  /**
   * Remove an appManagementPolicy policy object from an application or service principal object. When you remove the appManagementPolicy, the application or service principal adopts the tenant-wide tenantAppManagementPolicy setting.
   */
  'DELETE /applications/{application-id}/appManagementPolicies/{appManagementPolicy-id}/$ref': Operation<
    '/applications/{application-id}/appManagementPolicies/{appManagementPolicy-id}/$ref',
    'delete'
  >;
  /**
   * The appManagementPolicy applied to this application.
   */
  'GET /applications/{application-id}/appManagementPolicies/$ref': Operation<
    '/applications/{application-id}/appManagementPolicies/$ref',
    'get'
  >;
  /**
   * Assign an appManagementPolicy policy object to an application or service principal object. The application or service principal adopts this policy over the tenant-wide tenantAppManagementPolicy setting. Only one policy object can be assigned to an application or service principal.
   */
  'POST /applications/{application-id}/appManagementPolicies/$ref': Operation<
    '/applications/{application-id}/appManagementPolicies/$ref',
    'post'
  >;
}
