// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Clear the application&#x27;s presence session for a user. If it is the user&#x27;s only presence session, the user&#x27;s presence will change to Offline/Offline. For details about presences sessions, see presence: setPresence.
   */
  'POST /users/{user-id}/presence/clearPresence': Operation<
    '/users/{user-id}/presence/clearPresence',
    'post'
  >;
}
