// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'delete'>;
  /**
   * Get a user&#x27;s presence information.
   */
  'GET /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'get'>;
  /**
   */
  'PATCH /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'patch'>;
}
