// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/virtualEvents/events/{virtualEvent-id}/sessions/{virtualEventSession-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/$count": Operation<
    "/solutions/virtualEvents/events/{virtualEvent-id}/sessions/{virtualEventSession-id}/attendanceReports/{meetingAttendanceReport-id}/attendanceRecords/$count",
    "get"
  >;
}
