export interface AIMessageEntity {
  readonly type: 'https://schema.org/Message';

  /**
   * Required as 'Message'
   */
  '@type': 'Message';

  /**
   * Required as 'https://schema.org
   */
  '@context': 'https://schema.org';

  /**
   * Indicate that the content was generated by AI.
   */
  additionalType?: ('AIGeneratedContent' | Omit<string, 'AIGeneratedContent'>)[];

  /**
   * other properties
   */
  [key: string]: any;
}
