// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The calendar that contains the event. Navigation property. Read-only.
   */
  'GET /me/calendars/{calendar-id}/events/{event-id}/calendar': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}/calendar',
    'get'
  >;
}
