// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}',
    'delete'
  >;
  /**
   * The events in the calendar. Navigation property. Read-only.
   */
  'GET /me/calendars/{calendar-id}/events': Operation<'/me/calendars/{calendar-id}/events', 'get'>;
  /**
   * The events in the calendar. Navigation property. Read-only.
   */
  'GET /me/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}',
    'patch'
  >;
  /**
   * Use this API to create a new event in a calendar. The calendar can be one for a user, or the default calendar of a Microsoft 365 group.
   */
  'POST /me/calendars/{calendar-id}/events': Operation<
    '/me/calendars/{calendar-id}/events',
    'post'
  >;
}
