// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/chats/{chat-id}/tabs/$count': Operation<'/me/chats/{chat-id}/tabs/$count', 'get'>;
}
