// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/me/chats/{chat-id}/tabs/{teamsTab-id}',
    'delete'
  >;
  /**
   * A collection of all the tabs in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/tabs': Operation<'/me/chats/{chat-id}/tabs', 'get'>;
  /**
   * A collection of all the tabs in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/me/chats/{chat-id}/tabs/{teamsTab-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/me/chats/{chat-id}/tabs/{teamsTab-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/tabs': Operation<'/me/chats/{chat-id}/tabs', 'post'>;
}
