// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/me/chats/{chat-id}/members/{conversationMember-id}',
    'delete'
  >;
  /**
   * List all conversation members in a chat. This method supports federation. For one-on-one chats, at least one chat member must belong to the tenant the request initiates from. For group chats, the chat must be initiated by a user in the tenant the request initiates from.
   */
  'GET /me/chats/{chat-id}/members': Operation<'/me/chats/{chat-id}/members', 'get'>;
  /**
   * A collection of all the members in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/me/chats/{chat-id}/members/{conversationMember-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/me/chats/{chat-id}/members/{conversationMember-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/members': Operation<'/me/chats/{chat-id}/members', 'post'>;
}
