// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/bookingBusinesses/$count": Operation<
    "/solutions/bookingBusinesses/$count",
    "get"
  >;
}
