// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete the specified bookingCustomer object.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}',
    'delete'
  >;
  /**
   * Get a list of bookingCustomer objects of a business.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/customers': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customers',
    'get'
  >;
  /**
   * Get the properties and relationships of a bookingCustomer object.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingCustomer object.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customers/{bookingCustomerBase-id}',
    'patch'
  >;
  /**
   * Create a new bookingCustomer object.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/customers': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customers',
    'post'
  >;
}
