// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a bookingCustomQuestion object.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}',
    'delete'
  >;
  /**
   * Get the bookingCustomQuestion resources associated with a bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions',
    'get'
  >;
  /**
   * Read the properties and relationships of a bookingCustomQuestion object.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingCustomQuestion object.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions/{bookingCustomQuestion-id}',
    'patch'
  >;
  /**
   * Create a new bookingCustomQuestion object.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/customQuestions',
    'post'
  >;
}
