// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Get the availability information of staff members of a Microsoft Bookings calendar.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/getStaffAvailability': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/getStaffAvailability',
    'post'
  >;
}
