// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a bookingBusiness object.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}',
    'delete'
  >;
  /**
   * Get a collection of bookingBusiness objects that has been created for the tenant. This operation returns only the id and displayName of each Microsoft Bookings business in the collection. For performance considerations, it does not return other properties. You can get the other properties of a Bookings business by specifying its id in a GET operation.
   */
  'GET /solutions/bookingBusinesses': Operation<'/solutions/bookingBusinesses', 'get'>;
  /**
   * Get the properties and relationships of a bookingBusiness object.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingBusiness object.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}',
    'patch'
  >;
  /**
   * Create a new Microsoft Bookings business in a tenant. This is the first step in setting up a Bookings business where you must specify the business display name. You can include other information such as business address, web site address, and scheduling policy, or set that information later by updating the bookingBusiness.
   */
  'POST /solutions/bookingBusinesses': Operation<'/solutions/bookingBusinesses', 'post'>;
}
