// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Make the scheduling page of a business available to external customers. Set the isPublished property to true, and the publicUrl property to the URL of the scheduling page.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/publish': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/publish',
    'post'
  >;
}
