// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a bookingService object in the specified bookingBusiness.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}',
    'delete'
  >;
  /**
   * Get a list of bookingService objects in the specified bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/services': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/services',
    'get'
  >;
  /**
   * Get the properties and relationships of a bookingService object in the specified bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingService object in the specified bookingBusiness. The following are some examples you can customize for a service:
- Price
- Typical length of an appointment
- Reminders
- Any time buffer to set up before or finish up after the service
- Scheduling policy parameters, such as minimum notice to book or cancel, and whether customers can select specific staff members for an appointment.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}',
    'patch'
  >;
  /**
   * Create a new bookingService for the specified bookingBusiness.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/services': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/services',
    'post'
  >;
}
