// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a bookingStaffMember in the specified bookingBusiness.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}',
    'delete'
  >;
  /**
   * Get a list of bookingStaffMember objects in the specified bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers',
    'get'
  >;
  /**
   * Get the properties and relationships of a bookingStaffMember in the specified bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingStaffMember in the specified bookingBusiness.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers/{bookingStaffMemberBase-id}',
    'patch'
  >;
  /**
   * Create a new bookingStaffMember in the specified bookingBusiness.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/staffMembers',
    'post'
  >;
}
