// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/$count": Operation<
    "/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/extensions/$count",
    "get"
  >;
}
