// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}',
    'delete'
  >;
  /**
   * The list of Exchange protection policies in the tenant.
   */
  'GET /solutions/backupRestore/exchangeProtectionPolicies': Operation<
    '/solutions/backupRestore/exchangeProtectionPolicies',
    'get'
  >;
  /**
   * The list of Exchange protection policies in the tenant.
   */
  'GET /solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}',
    'get'
  >;
  /**
   * Update an Exchange protection policy. This method adds a mailboxprotectionunit to or removes it from the protection policy.
   */
  'PATCH /solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/exchangeProtectionPolicies/{exchangeProtectionPolicy-id}',
    'patch'
  >;
  /**
   * Create a protection policy for the Exchange service in a Microsoft 365 tenant. The policy is set to inactive when it is created. Users can also provide a list of protection units under the policy.
   */
  'POST /solutions/backupRestore/exchangeProtectionPolicies': Operation<
    '/solutions/backupRestore/exchangeProtectionPolicies',
    'post'
  >;
}
