// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Send an activity feed notification to a user. For more information, see sending Teams activity notifications.
   */
  'POST /users/{user-id}/teamwork/sendActivityNotification': Operation<
    '/users/{user-id}/teamwork/sendActivityNotification',
    'post'
  >;
}
