// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   * Remove a tokenIssuancePolicy from an application.
   */
  "DELETE /applications/{application-id}/tokenIssuancePolicies/$ref": Operation<
    "/applications/{application-id}/tokenIssuancePolicies/$ref",
    "delete"
  >;
  /**
   * Remove a tokenIssuancePolicy from an application.
   */
  "DELETE /applications/{application-id}/tokenIssuancePolicies/{tokenIssuancePolicy-id}/$ref": Operation<
    "/applications/{application-id}/tokenIssuancePolicies/{tokenIssuancePolicy-id}/$ref",
    "delete"
  >;
  /**
   * List the tokenIssuancePolicy objects that are assigned to an application.
   */
  "GET /applications/{application-id}/tokenIssuancePolicies/$ref": Operation<
    "/applications/{application-id}/tokenIssuancePolicies/$ref",
    "get"
  >;
  /**
   * Assign a tokenIssuancePolicy to an application.
   */
  "POST /applications/{application-id}/tokenIssuancePolicies/$ref": Operation<
    "/applications/{application-id}/tokenIssuancePolicies/$ref",
    "post"
  >;
}
