// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'delete'
  >;
  /**
   * Replies for a specified message. Supports $expand for channel messages.
   */
  'GET /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies',
    'get'
  >;
  /**
   * Replies for a specified message. Supports $expand for channel messages.
   */
  'GET /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies/{chatMessage-id1}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/replies',
    'post'
  >;
}
