// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   * The unique identifier for an entity. Read-only.
   */
  "DELETE /chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value": Operation<
    "/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value",
    "delete"
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  "GET /chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value": Operation<
    "/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value",
    "get"
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  "PUT /chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value": Operation<
    "/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/{chatMessageHostedContent-id}/$value",
    "put"
  >;
}
