// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Remove a conversationMember from a chat.
   */
  'DELETE /chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/chats/{chat-id}/members/{conversationMember-id}',
    'delete'
  >;
  /**
   * List all conversation members in a chat or channel.
   */
  'GET /chats/{chat-id}/members': Operation<'/chats/{chat-id}/members', 'get'>;
  /**
   * Retrieve a conversationMember from a chat or channel.
   */
  'GET /chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/chats/{chat-id}/members/{conversationMember-id}',
    'get'
  >;
  /**
   */
  'PATCH /chats/{chat-id}/members/{conversationMember-id}': Operation<
    '/chats/{chat-id}/members/{conversationMember-id}',
    'patch'
  >;
  /**
   * Add a conversationMember to a chat.
   */
  'POST /chats/{chat-id}/members': Operation<'/chats/{chat-id}/members', 'post'>;
}
