// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}': Operation<
    '/solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}',
    'delete'
  >;
  /**
   * The list of SharePoint restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/sharePointRestoreSessions': Operation<
    '/solutions/backupRestore/sharePointRestoreSessions',
    'get'
  >;
  /**
   * The list of SharePoint restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}': Operation<
    '/solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}': Operation<
    '/solutions/backupRestore/sharePointRestoreSessions/{sharePointRestoreSession-id}',
    'patch'
  >;
  /**
   * Create a new sharePointRestoreSession object.
   */
  'POST /solutions/backupRestore/sharePointRestoreSessions': Operation<
    '/solutions/backupRestore/sharePointRestoreSessions',
    'post'
  >;
}
