// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/sessions/{virtualEventSession-id}/attendanceReports/$count': Operation<
    '/solutions/virtualEvents/townhalls/{virtualEventTownhall-id}/sessions/{virtualEventSession-id}/attendanceReports/$count',
    'get'
  >;
}
