// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Clear the preferred availability and activity status for a user.
   */
  'POST /communications/presences/{presence-id}/clearUserPreferredPresence': Operation<
    '/communications/presences/{presence-id}/clearUserPreferredPresence',
    'post'
  >;
}
