// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/presences/$count": Operation<
    "/communications/presences/$count",
    "get"
  >;
}
