// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/presences/{presence-id}': Operation<
    '/communications/presences/{presence-id}',
    'delete'
  >;
  /**
   * Get a user&#x27;s presence information.
   */
  'GET /communications/presences': Operation<'/communications/presences', 'get'>;
  /**
   * Get a user&#x27;s presence information.
   */
  'GET /communications/presences/{presence-id}': Operation<
    '/communications/presences/{presence-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/presences/{presence-id}': Operation<
    '/communications/presences/{presence-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/presences': Operation<'/communications/presences', 'post'>;
}
