// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Set the state of a user&#x27;s presence session as an application.
   */
  'POST /communications/presences/{presence-id}/setPresence': Operation<
    '/communications/presences/{presence-id}/setPresence',
    'post'
  >;
}
