// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /me/calendar/calendarPermissions/$count": Operation<
    "/me/calendar/calendarPermissions/$count",
    "get"
  >;
}
