// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   * List all operators supported in the scoping filters.
   */
  "GET /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/filterOperators()": Operation<
    "/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/filterOperators()",
    "get"
  >;
}
