// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema',
    'delete'
  >;
  /**
   * Default synchronization schema for the jobs based on this template.
   */
  'GET /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema',
    'get'
  >;
  /**
   */
  'PATCH /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema',
    'patch'
  >;
}
