// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}',
    'delete'
  >;
  /**
   * A collection of all the messages in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/messages': Operation<'/me/chats/{chat-id}/messages', 'get'>;
  /**
   * A collection of all the messages in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/messages': Operation<'/me/chats/{chat-id}/messages', 'post'>;
}
