// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/primaryChannel/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/primaryChannel/members/{conversationMember-id}',
    'delete'
  >;
  /**
   * A collection of membership records associated with the channel.
   */
  'GET /teams/{team-id}/primaryChannel/members': Operation<
    '/teams/{team-id}/primaryChannel/members',
    'get'
  >;
  /**
   * A collection of membership records associated with the channel.
   */
  'GET /teams/{team-id}/primaryChannel/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/primaryChannel/members/{conversationMember-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/primaryChannel/members/{conversationMember-id}': Operation<
    '/teams/{team-id}/primaryChannel/members/{conversationMember-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/primaryChannel/members': Operation<
    '/teams/{team-id}/primaryChannel/members',
    'post'
  >;
}
