// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/$count": Operation<
    "/appCatalogs/teamsApps/{teamsApp-id}/appDefinitions/$count",
    "get"
  >;
}
