// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents': Operation<'/solutions/virtualEvents', 'delete'>;
  /**
   */
  'GET /solutions/virtualEvents': Operation<'/solutions/virtualEvents', 'get'>;
  /**
   */
  'PATCH /solutions/virtualEvents': Operation<'/solutions/virtualEvents', 'patch'>;
}
