// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Add multiple members in a single request to a team. The response provides details about which memberships could and couldn&#x27;t be created.
   */
  'POST /users/{user-id}/chats/{chat-id}/members/add': Operation<
    '/users/{user-id}/chats/{chat-id}/members/add',
    'post'
  >;
}
