// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /teamwork/workforceIntegrations/$count": Operation<
    "/teamwork/workforceIntegrations/$count",
    "get"
  >;
}
