// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/$count": Operation<
    "/communications/onlineMeetings/{onlineMeeting-id}/attendanceReports/$count",
    "get"
  >;
}
