// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Uninstalls an app from the specified team.
   */
  'DELETE /teams/{team-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/teams/{team-id}/installedApps/{teamsAppInstallation-id}',
    'delete'
  >;
  /**
   * Retrieve a list of apps installed in the specified team.
   */
  'GET /teams/{team-id}/installedApps': Operation<'/teams/{team-id}/installedApps', 'get'>;
  /**
   * Retrieve the app installed in the specified team.
   */
  'GET /teams/{team-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/teams/{team-id}/installedApps/{teamsAppInstallation-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/teams/{team-id}/installedApps/{teamsAppInstallation-id}',
    'patch'
  >;
  /**
   * Install an app to the specified team.
   */
  'POST /teams/{team-id}/installedApps': Operation<'/teams/{team-id}/installedApps', 'post'>;
}
