// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * The app that is installed.
   */
  'GET /teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsApp': Operation<
    '/teams/{team-id}/installedApps/{teamsAppInstallation-id}/teamsApp',
    'get'
  >;
}
