// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Upgrade an app installation within a chat.
   */
  'POST /teams/{team-id}/installedApps/{teamsAppInstallation-id}/upgrade': Operation<
    '/teams/{team-id}/installedApps/{teamsAppInstallation-id}/upgrade',
    'post'
  >;
}
