// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload',
    'delete'
  >;
  /**
   * The bulk upload operation for the job.
   */
  'GET /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload',
    'get'
  >;
  /**
   */
  'PATCH /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload',
    'patch'
  >;
}
