// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}',
    'delete'
  >;
  /**
   * Performs synchronization by periodically running in the background, polling for changes in one directory, and pushing them to another directory.
   */
  'GET /applications/{application-id}/synchronization/jobs': Operation<
    '/applications/{application-id}/synchronization/jobs',
    'get'
  >;
  /**
   * Performs synchronization by periodically running in the background, polling for changes in one directory, and pushing them to another directory.
   */
  'GET /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}',
    'get'
  >;
  /**
   */
  'PATCH /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}',
    'patch'
  >;
  /**
   */
  'POST /applications/{application-id}/synchronization/jobs': Operation<
    '/applications/{application-id}/synchronization/jobs',
    'post'
  >;
}
