// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Temporarily stop a running synchronization job. All the progress, including job state, is persisted, and the job will continue from where it left off when a start call is made.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/pause': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/pause',
    'post'
  >;
}
