// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Select a user and provision the account on-demand. The rate limit for this API is 5 requests per 10 seconds.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/provisionOnDemand': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/provisionOnDemand',
    'post'
  >;
}
