// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Restart a stopped synchronization job, forcing it to reprocess all the objects in the directory. Optionally clears existing the synchronization state and previous errors.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/restart': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/restart',
    'post'
  >;
}
