// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Start an existing synchronization job. If the job is in a paused state, it continues processing changes from the point where it was paused. If the job is in quarantine, the quarantine status is cleared. Don&#x27;t create scripts to call the start job continuously while it&#x27;s running because that can cause the service to stop running. Use the start job only when the job is currently paused or in quarantine.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/start': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/start',
    'post'
  >;
}
