// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /applications/{application-id}/synchronization/jobs/validateCredentials': Operation<
    '/applications/{application-id}/synchronization/jobs/validateCredentials',
    'post'
  >;
  /**
   * Validate that the credentials are valid in the tenant.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/validateCredentials': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/validateCredentials',
    'post'
  >;
}
