// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /chats/{chat-id}/messages/{chatMessage-id}/replies/$count": Operation<
    "/chats/{chat-id}/messages/{chatMessage-id}/replies/$count",
    "get"
  >;
}
