// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /communications/callRecords/{callRecord-id}/sessions/$count': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/$count',
    'get'
  >;
}
