// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/callRecords/{callRecord-id}/sessions/{session-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}',
    'delete'
  >;
  /**
   * Retrieve the list of sessions associated with a callRecord object. If the sessions list is truncated, a sessions@odata.nextLink value will be provided to retrieve the next page of sessions. The maximum page size for sessions is 60 entries.
   */
  'GET /communications/callRecords/{callRecord-id}/sessions': Operation<
    '/communications/callRecords/{callRecord-id}/sessions',
    'get'
  >;
  /**
   * List of sessions involved in the call. Peer-to-peer calls typically only have one session, whereas group calls typically have at least one session per participant. Read-only. Nullable.
   */
  'GET /communications/callRecords/{callRecord-id}/sessions/{session-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/callRecords/{callRecord-id}/sessions/{session-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/callRecords/{callRecord-id}/sessions': Operation<
    '/communications/callRecords/{callRecord-id}/sessions',
    'post'
  >;
}
