// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}',
    'delete'
  >;
  /**
   * The list of segments involved in the session. Read-only. Nullable.
   */
  'GET /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments',
    'get'
  >;
  /**
   * The list of segments involved in the session. Read-only. Nullable.
   */
  'GET /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/{segment-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments': Operation<
    '/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments',
    'post'
  >;
}
