// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Dismiss a reminder that has been triggered for an event in a user calendar.
   */
  'POST /me/calendar/events/{event-id}/dismissReminder': Operation<
    '/me/calendar/events/{event-id}/dismissReminder',
    'post'
  >;
}
