// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendar/events/{event-id}': Operation<'/me/calendar/events/{event-id}', 'delete'>;
  /**
   * Retrieve a list of events in a calendar. The calendar can be one for a user, or the default calendar of a Microsoft 365 group. The list of events contains single instance meetings and series masters. To get expanded event instances, you can get the calendar view, or
get the instances of an event.
   */
  'GET /me/calendar/events': Operation<'/me/calendar/events', 'get'>;
  /**
   * The events in the calendar. Navigation property. Read-only.
   */
  'GET /me/calendar/events/{event-id}': Operation<'/me/calendar/events/{event-id}', 'get'>;
  /**
   */
  'PATCH /me/calendar/events/{event-id}': Operation<'/me/calendar/events/{event-id}', 'patch'>;
  /**
   */
  'POST /me/calendar/events': Operation<'/me/calendar/events', 'post'>;
}
