// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/primaryChannel/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}',
    'delete'
  >;
  /**
   * A collection of all the tabs in the channel. A navigation property.
   */
  'GET /teams/{team-id}/primaryChannel/tabs': Operation<
    '/teams/{team-id}/primaryChannel/tabs',
    'get'
  >;
  /**
   * A collection of all the tabs in the channel. A navigation property.
   */
  'GET /teams/{team-id}/primaryChannel/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/primaryChannel/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/primaryChannel/tabs/{teamsTab-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/primaryChannel/tabs': Operation<
    '/teams/{team-id}/primaryChannel/tabs',
    'post'
  >;
}
