// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Dismiss a reminder that has been triggered for an event in a user calendar.
   */
  'POST /me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/dismissReminder': Operation<
    '/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/dismissReminder',
    'post'
  >;
}
