// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Tentatively accept the specified event in a user calendar. If the event allows proposals for new times, on responding tentative to the event, an invitee can choose to suggest an alternative time by including the proposedNewTime parameter. For more information on how to propose a time, and how to receive and accept a new time proposal, see Propose new meeting times.
   */
  'POST /me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/tentativelyAccept': Operation<
    '/me/calendars/{calendar-id}/calendarView/{event-id}/instances/{event-id1}/tentativelyAccept',
    'post'
  >;
}
