// DO NOT EDIT THIS FILE
import type { Operation } from './../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /applicationTemplates/$count': Operation<'/applicationTemplates/$count', 'get'>;
}
