// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Add an instance of an application from the Microsoft Entra application gallery into your directory. For non-gallery apps, use an application template with one of the following IDs to configure different single sign-on (SSO) modes like SAML SSO and password-based SSO.
   */
  'POST /applicationTemplates/{applicationTemplate-id}/instantiate': Operation<
    '/applicationTemplates/{applicationTemplate-id}/instantiate',
    'post'
  >;
}
