// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}',
    'delete'
  >;
  /**
   * The list of SharePoint protection policies in the tenant.
   */
  'GET /solutions/backupRestore/sharePointProtectionPolicies': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies',
    'get'
  >;
  /**
   * The list of SharePoint protection policies in the tenant.
   */
  'GET /solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}',
    'get'
  >;
  /**
   * Update a SharePoint protection policy. This method adds a siteprotectionunit to or removes it from the protection policy.
   */
  'PATCH /solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}',
    'patch'
  >;
  /**
   * Create a protection policy for a M365 service SharePoint. Policy will be created in inactive state. User can also provide a list of protection units under the policy.
   */
  'POST /solutions/backupRestore/sharePointProtectionPolicies': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies',
    'post'
  >;
}
