// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/$count": Operation<
    "/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/hostedContents/$count",
    "get"
  >;
}
