// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Get the list of channels either in this team or shared with this team (incoming channels).
   */
  'GET /teams/{team-id}/allChannels': Operation<'/teams/{team-id}/allChannels', 'get'>;
  /**
   * List of channels either hosted in or shared with the team (incoming channels).
   */
  'GET /teams/{team-id}/allChannels/{channel-id}': Operation<
    '/teams/{team-id}/allChannels/{channel-id}',
    'get'
  >;
}
