// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Get the list of incoming channels (channels shared with a team).
   */
  'GET /teams/{team-id}/incomingChannels': Operation<'/teams/{team-id}/incomingChannels', 'get'>;
  /**
   * List of channels shared with the team.
   */
  'GET /teams/{team-id}/incomingChannels/{channel-id}': Operation<
    '/teams/{team-id}/incomingChannels/{channel-id}',
    'get'
  >;
}
