// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}': Operation<'/teams/{team-id}', 'delete'>;
  /**
   * List all teams in an organization.
   */
  'GET /teams': Operation<'/teams', 'get'>;
  /**
   * Retrieve the properties and relationships of the specified team.
   */
  'GET /teams/{team-id}': Operation<'/teams/{team-id}', 'get'>;
  /**
   * Update the properties of the specified team.
   */
  'PATCH /teams/{team-id}': Operation<'/teams/{team-id}', 'patch'>;
  /**
   * Create a new team.
   */
  'POST /teams': Operation<'/teams', 'post'>;
}
