// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/operations/{teamsAsyncOperation-id}': Operation<
    '/teams/{team-id}/operations/{teamsAsyncOperation-id}',
    'delete'
  >;
  /**
   * The async operations that ran or are running on this team.
   */
  'GET /teams/{team-id}/operations': Operation<'/teams/{team-id}/operations', 'get'>;
  /**
   * The async operations that ran or are running on this team.
   */
  'GET /teams/{team-id}/operations/{teamsAsyncOperation-id}': Operation<
    '/teams/{team-id}/operations/{teamsAsyncOperation-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/operations/{teamsAsyncOperation-id}': Operation<
    '/teams/{team-id}/operations/{teamsAsyncOperation-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/operations': Operation<'/teams/{team-id}/operations', 'post'>;
}
