// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'delete'
  >;
  /**
   * List all resource-specific permission grants on the team. This list specifies the Microsoft Entra apps that have access to the team, along with each app&#x27;s corresponding type of resource-specific access.
   */
  'GET /teams/{team-id}/permissionGrants': Operation<'/teams/{team-id}/permissionGrants', 'get'>;
  /**
   * A collection of permissions granted to apps to access the team.
   */
  'GET /teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/teams/{team-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/permissionGrants': Operation<'/teams/{team-id}/permissionGrants', 'post'>;
}
