// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * The template this team was created from. See available templates.
   */
  'GET /teams/{team-id}/template': Operation<'/teams/{team-id}/template', 'get'>;
}
