// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}',
    'delete'
  >;
  /**
   * The list of OneDrive for Business protection policies in the tenant.
   */
  'GET /solutions/backupRestore/oneDriveForBusinessProtectionPolicies': Operation<
    '/solutions/backupRestore/oneDriveForBusinessProtectionPolicies',
    'get'
  >;
  /**
   * The list of OneDrive for Business protection policies in the tenant.
   */
  'GET /solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}',
    'get'
  >;
  /**
   * Update the protection policy for the OneDrive service in Microsoft 365. This method adds a driveProtectionUnit to or removes it from a oneDriveForBusinessProtectionPolicy object.
   */
  'PATCH /solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessProtectionPolicies/{oneDriveForBusinessProtectionPolicy-id}',
    'patch'
  >;
  /**
   * Create a protection policy for the OneDrive service in Microsoft 365. When the policy is created, its state is set to inactive. Users can also provide a list of protection units under the policy.
   */
  'POST /solutions/backupRestore/oneDriveForBusinessProtectionPolicies': Operation<
    '/solutions/backupRestore/oneDriveForBusinessProtectionPolicies',
    'post'
  >;
}
