// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/primaryChannel': Operation<'/teams/{team-id}/primaryChannel', 'delete'>;
  /**
   * Get the default channel, General, of a team.
   */
  'GET /teams/{team-id}/primaryChannel': Operation<'/teams/{team-id}/primaryChannel', 'get'>;
  /**
   */
  'PATCH /teams/{team-id}/primaryChannel': Operation<'/teams/{team-id}/primaryChannel', 'patch'>;
}
