// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/$count': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/$count',
    'get'
  >;
}
