// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}',
    'delete'
  >;
  /**
   * Get a list of all registration records of a webinar.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations',
    'get'
  >;
  /**
   * Get the properties and relationships of a virtualEventRegistration object.
   */
  'GET /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations/{virtualEventRegistration-id}',
    'patch'
  >;
  /**
   * Create a registration record for a registrant of a webinar. This method registers the person for the webinar.
   */
  'POST /solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations': Operation<
    '/solutions/virtualEvents/webinars/{virtualEventWebinar-id}/registrations',
    'post'
  >;
}
