// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/bookingBusinesses/{bookingBusiness-id}/appointments/$count": Operation<
    "/solutions/bookingBusinesses/{bookingBusiness-id}/appointments/$count",
    "get"
  >;
}
