// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a bookingAppointment in the specified bookingBusiness.
   */
  'DELETE /solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}',
    'delete'
  >;
  /**
   * Get a list of bookingAppointment objects for the specified bookingBusiness.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/appointments': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/appointments',
    'get'
  >;
  /**
   * Get the properties and relationships of a bookingAppointment object in the specified bookingBusiness. The start and end properties are always returned in UTC.
   */
  'GET /solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}',
    'get'
  >;
  /**
   * Update the properties of a bookingAppointment object in the specified bookingBusiness.
   */
  'PATCH /solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/appointments/{bookingAppointment-id}',
    'patch'
  >;
  /**
   * Create a new bookingAppointment for the specified bookingBusiness.
   */
  'POST /solutions/bookingBusinesses/{bookingBusiness-id}/appointments': Operation<
    '/solutions/bookingBusinesses/{bookingBusiness-id}/appointments',
    'post'
  >;
}
