// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/sharedWithTeams/$count": Operation<
    "/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/sharedWithTeams/$count",
    "get"
  >;
}
