// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../common.d.ts";

export interface Endpoints {
  /**
   * The bulk upload operation for the job.
   */
  "DELETE /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value": Operation<
    "/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value",
    "delete"
  >;
  /**
   * The bulk upload operation for the job.
   */
  "GET /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value": Operation<
    "/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value",
    "get"
  >;
  /**
   * The bulk upload operation for the job.
   */
  "PUT /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value": Operation<
    "/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/bulkUpload/$value",
    "put"
  >;
}
