// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}',
    'delete'
  >;
  /**
   * The permissions of the users with whom the calendar is shared.
   */
  'GET /me/calendars/{calendar-id}/calendarPermissions': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions',
    'get'
  >;
  /**
   * The permissions of the users with whom the calendar is shared.
   */
  'GET /me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions/{calendarPermission-id}',
    'patch'
  >;
  /**
   */
  'POST /me/calendars/{calendar-id}/calendarPermissions': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions',
    'post'
  >;
}
