// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Get the free/busy availability information for a collection of users, distributions lists, or resources (rooms or equipment) for a specified time period.
   */
  'POST /me/calendars/{calendar-id}/getSchedule': Operation<
    '/me/calendars/{calendar-id}/getSchedule',
    'post'
  >;
}
