// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendars/{calendar-id}': Operation<'/me/calendars/{calendar-id}', 'delete'>;
  /**
   * Get all the user&#x27;s calendars (/calendars navigation property), get the calendars from the default calendar group or from a specific calendar group.
   */
  'GET /me/calendars': Operation<'/me/calendars', 'get'>;
  /**
   * The user&#x27;s calendars. Read-only. Nullable.
   */
  'GET /me/calendars/{calendar-id}': Operation<'/me/calendars/{calendar-id}', 'get'>;
  /**
   */
  'PATCH /me/calendars/{calendar-id}': Operation<'/me/calendars/{calendar-id}', 'patch'>;
  /**
   * Create a new calendar for a user.
   */
  'POST /me/calendars': Operation<'/me/calendars', 'post'>;
}
