// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /applications/{application-id}/owners/graph.appRoleAssignment': Operation<
    '/applications/{application-id}/owners/graph.appRoleAssignment',
    'get'
  >;
  /**
   */
  'GET /applications/{application-id}/owners/{directoryObject-id}/graph.appRoleAssignment': Operation<
    '/applications/{application-id}/owners/{directoryObject-id}/graph.appRoleAssignment',
    'get'
  >;
}
