// DO NOT EDIT THIS FILE
import type { Operation } from "./../common.d.ts";

export interface Endpoints {
  /**
   * Get all messages from all chats that a user is a participant in, including one-on-one chats, group chats, and meeting chats.
   */
  "GET /chats/getAllMessages()": Operation<"/chats/getAllMessages()", "get">;
}
