// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Hide a chat for a user.
   */
  'POST /chats/{chat-id}/hideForUser': Operation<'/chats/{chat-id}/hideForUser', 'post'>;
}
