// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Soft-delete a chat. When invoked with delegated permissions, this operation only works for tenant admins and Teams service admins.
   */
  'DELETE /chats/{chat-id}': Operation<'/chats/{chat-id}', 'delete'>;
  /**
   * Retrieve the list of chats that the user is part of. This method supports federation. When a user ID is provided, the calling application must belong to the same tenant that the user belongs to.
   */
  'GET /chats': Operation<'/chats', 'get'>;
  /**
   * Retrieve a single chat (without its messages). This method supports federation. To access a chat, at least one chat member must belong to the tenant the request initiated from.
   */
  'GET /chats/{chat-id}': Operation<'/chats/{chat-id}', 'get'>;
  /**
   * Update the properties of a chat object.
   */
  'PATCH /chats/{chat-id}': Operation<'/chats/{chat-id}', 'patch'>;
  /**
   * Create a new chat object.
   */
  'POST /chats': Operation<'/chats', 'post'>;
}
