// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Mark a chat as unread for a user.
   */
  'POST /chats/{chat-id}/markChatUnreadForUser': Operation<
    '/chats/{chat-id}/markChatUnreadForUser',
    'post'
  >;
}
