// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Mark a chat as read for a user.
   */
  'POST /chats/{chat-id}/markChatReadForUser': Operation<
    '/chats/{chat-id}/markChatReadForUser',
    'post'
  >;
}
