// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'delete'
  >;
  /**
   * List all resource-specific permission grants on the chat. This list specifies the Microsoft Entra apps that have access to the chat, along with the corresponding resource-specific access that each app has.
   */
  'GET /chats/{chat-id}/permissionGrants': Operation<'/chats/{chat-id}/permissionGrants', 'get'>;
  /**
   * A collection of permissions granted to apps for the chat.
   */
  'GET /chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'get'
  >;
  /**
   */
  'PATCH /chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'patch'
  >;
  /**
   */
  'POST /chats/{chat-id}/permissionGrants': Operation<'/chats/{chat-id}/permissionGrants', 'post'>;
}
