// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Unhide a chat for a user.
   */
  'POST /chats/{chat-id}/unhideForUser': Operation<'/chats/{chat-id}/unhideForUser', 'post'>;
}
