// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Clear the preferred availability and activity status for a user.
   */
  'POST /me/presence/clearUserPreferredPresence': Operation<
    '/me/presence/clearUserPreferredPresence',
    'post'
  >;
}
