// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/presence': Operation<'/me/presence', 'delete'>;
  /**
   * Get a user&#x27;s presence information.
   */
  'GET /me/presence': Operation<'/me/presence', 'get'>;
  /**
   */
  'PATCH /me/presence': Operation<'/me/presence', 'patch'>;
}
