// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Set the state of a user&#x27;s presence session as an application.
   */
  'POST /me/presence/setPresence': Operation<'/me/presence/setPresence', 'post'>;
}
