// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * The collection of the user&#x27;s profile photos in different sizes. Read-only.
   */
  'GET /me/photos': Operation<'/me/photos', 'get'>;
  /**
   * The collection of the user&#x27;s profile photos in different sizes. Read-only.
   */
  'GET /me/photos/{profilePhoto-id}': Operation<'/me/photos/{profilePhoto-id}', 'get'>;
}
