// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/backupRestore/mailboxInclusionRules/$count": Operation<
    "/solutions/backupRestore/mailboxInclusionRules/$count",
    "get"
  >;
}
