// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The calendar that contains the event. Navigation property. Read-only.
   */
  'GET /me/calendar/calendarView/{event-id}/calendar': Operation<
    '/me/calendar/calendarView/{event-id}/calendar',
    'get'
  >;
}
