// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendar/calendarView/$count': Operation<'/me/calendar/calendarView/$count', 'get'>;
}
