// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Get the occurrences, exceptions and single instances of events in a calendar view defined by a time range,
from a user&#x27;s default calendar (../me/calendarView) or some other calendar of the user&#x27;s.
   */
  'GET /me/calendar/calendarView': Operation<'/me/calendar/calendarView', 'get'>;
  /**
   * The calendar view for the calendar. Navigation property. Read-only.
   */
  'GET /me/calendar/calendarView/{event-id}': Operation<
    '/me/calendar/calendarView/{event-id}',
    'get'
  >;
}
