// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Get the metadata for the location where the files of a channel are stored.
   */
  'GET /teams/{team-id}/channels/{channel-id}/filesFolder': Operation<
    '/teams/{team-id}/channels/{channel-id}/filesFolder',
    'get'
  >;
}
