// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'POST /appRoleAssignments/{appRoleAssignment-id}/checkMemberObjects': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}/checkMemberObjects',
    'post'
  >;
}
