// DO NOT EDIT THIS FILE
import type { Operation } from "./../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /appRoleAssignments/$count": Operation<
    "/appRoleAssignments/$count",
    "get"
  >;
}
