// DO NOT EDIT THIS FILE
import type { Operation } from "./..\common.d.ts";

export interface Endpoints {
  /**
   * Get newly created, updated, or deleted directory objects without performing a full read of the entire directoryObject collection. For more information, see Use delta query to track changes in Microsoft Graph data for details.
   */
  "GET /appRoleAssignments/delta()": Operation<
    "/appRoleAssignments/delta()",
    "get"
  >;
}
