// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Return all directory extension definitions that have been registered in a directory, including through multi-tenant apps. The following entities support extension properties:
   */
  'POST /appRoleAssignments/getAvailableExtensionProperties': Operation<
    '/appRoleAssignments/getAvailableExtensionProperties',
    'post'
  >;
}
