// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Return all IDs for the groups, administrative units, and directory roles that an object of one of the following types is a member of:
- user
- group
- service principal
- organizational contact
- device
- directory object This function is transitive. Only users and role-enabled groups can be members of directory roles.
   */
  'POST /appRoleAssignments/{appRoleAssignment-id}/getMemberObjects': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}/getMemberObjects',
    'post'
  >;
}
