// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /appRoleAssignments/{appRoleAssignment-id}': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}',
    'delete'
  >;
  /**
   */
  'GET /appRoleAssignments': Operation<'/appRoleAssignments', 'get'>;
  /**
   */
  'GET /appRoleAssignments/{appRoleAssignment-id}': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}',
    'get'
  >;
  /**
   */
  'PATCH /appRoleAssignments/{appRoleAssignment-id}': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}',
    'patch'
  >;
  /**
   */
  'POST /appRoleAssignments': Operation<'/appRoleAssignments', 'post'>;
}
