// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Restore a recently deleted application, group, servicePrincipal, administrative unit, or user object from deleted items. If an item was accidentally deleted, you can fully restore the item. However, security groups can&#x27;t be restored. Also, restoring an application doesn&#x27;t restore the associated service principal automatically. You must call this API to explicitly restore the deleted service principal. A recently deleted item remains available for up to 30 days. After 30 days, the item is permanently deleted.
   */
  'POST /appRoleAssignments/{appRoleAssignment-id}/restore': Operation<
    '/appRoleAssignments/{appRoleAssignment-id}/restore',
    'post'
  >;
}
