// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}': Operation<
    '/me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}',
    'delete'
  >;
  /**
   * A collection of all the pinned messages in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/pinnedMessages': Operation<'/me/chats/{chat-id}/pinnedMessages', 'get'>;
  /**
   * A collection of all the pinned messages in the chat. Nullable.
   */
  'GET /me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}': Operation<
    '/me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}': Operation<
    '/me/chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfo-id}',
    'patch'
  >;
  /**
   */
  'POST /me/chats/{chat-id}/pinnedMessages': Operation<
    '/me/chats/{chat-id}/pinnedMessages',
    'post'
  >;
}
