// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/onlineMeetings/{onlineMeeting-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}',
    'delete'
  >;
  /**
   * Retrieve the properties and relationships of an onlineMeeting object. For example, you can: Teams live event attendee report (deprecated) is an online meeting artifact. For details, see Online meeting artifacts and permissions.
   */
  'GET /communications/onlineMeetings': Operation<'/communications/onlineMeetings', 'get'>;
  /**
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/onlineMeetings/{onlineMeeting-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/onlineMeetings': Operation<'/communications/onlineMeetings', 'post'>;
}
