// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Add the large gallery view to a call.  For details about how to identify a large gallery view participant in a roster so that you can retrieve the relevant data to subscribe to the video feed, see Identify large gallery view participants in a roster.
   */
  'POST /communications/calls/{call-id}/addLargeGalleryView': Operation<
    '/communications/calls/{call-id}/addLargeGalleryView',
    'post'
  >;
}
