// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete the specified audioRoutingGroup.
   */
  'DELETE /communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}': Operation<
    '/communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}',
    'delete'
  >;
  /**
   * Retrieve a list of audioRoutingGroup objects.
   */
  'GET /communications/calls/{call-id}/audioRoutingGroups': Operation<
    '/communications/calls/{call-id}/audioRoutingGroups',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of an audioRoutingGroup object.
   */
  'GET /communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}': Operation<
    '/communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}',
    'get'
  >;
  /**
   * Modify sources and receivers of an audioRoutingGroup.
   */
  'PATCH /communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}': Operation<
    '/communications/calls/{call-id}/audioRoutingGroups/{audioRoutingGroup-id}',
    'patch'
  >;
  /**
   * Create a new audioRoutingGroup.
   */
  'POST /communications/calls/{call-id}/audioRoutingGroups': Operation<
    '/communications/calls/{call-id}/audioRoutingGroups',
    'post'
  >;
}
