// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Allow applications to share screen content with the participants of a group call.
   */
  'POST /communications/calls/{call-id}/changeScreenSharingRole': Operation<
    '/communications/calls/{call-id}/changeScreenSharingRole',
    'post'
  >;
}
