// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}': Operation<
    '/communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}',
    'delete'
  >;
  /**
   * Retrieve a list of contentSharingSession objects in a call.
   */
  'GET /communications/calls/{call-id}/contentSharingSessions': Operation<
    '/communications/calls/{call-id}/contentSharingSessions',
    'get'
  >;
  /**
   * Retrieve the properties of a contentSharingSession object in a call.
   */
  'GET /communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}': Operation<
    '/communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}': Operation<
    '/communications/calls/{call-id}/contentSharingSessions/{contentSharingSession-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/calls/{call-id}/contentSharingSessions': Operation<
    '/communications/calls/{call-id}/contentSharingSessions',
    'post'
  >;
}
