// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete or hang up an active call. For group calls, this will only delete your call leg and the underlying group call will still continue.
   */
  'DELETE /communications/calls/{call-id}': Operation<'/communications/calls/{call-id}', 'delete'>;
  /**
   * Retrieve the properties and relationships of a call object.
   */
  'GET /communications/calls': Operation<'/communications/calls', 'get'>;
  /**
   * Retrieve the properties and relationships of a call object.
   */
  'GET /communications/calls/{call-id}': Operation<'/communications/calls/{call-id}', 'get'>;
  /**
   */
  'PATCH /communications/calls/{call-id}': Operation<'/communications/calls/{call-id}', 'patch'>;
  /**
   * Create call enables your bot to create a new outgoing peer-to-peer or group call, or join an existing meeting. You need to register the calling bot and go through the list of permissions needed. This API supports the following PSTN scenarios:
   */
  'POST /communications/calls': Operation<'/communications/calls', 'post'>;
}
