// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Allows the application to mute itself. This is a server mute, meaning that the server will drop all audio packets for this participant, even if the participant continues to stream audio. For more details about how to handle mute operations, see muteParticipantOperation
   */
  'POST /communications/calls/{call-id}/mute': Operation<
    '/communications/calls/{call-id}/mute',
    'post'
  >;
}
