// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/calls/{call-id}/operations/{commsOperation-id}': Operation<
    '/communications/calls/{call-id}/operations/{commsOperation-id}',
    'delete'
  >;
  /**
   * Get the status of an operation that adds the large gallery view to a call.
   */
  'GET /communications/calls/{call-id}/operations': Operation<
    '/communications/calls/{call-id}/operations',
    'get'
  >;
  /**
   * Get the status of an operation that adds the large gallery view to a call.
   */
  'GET /communications/calls/{call-id}/operations/{commsOperation-id}': Operation<
    '/communications/calls/{call-id}/operations/{commsOperation-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/calls/{call-id}/operations/{commsOperation-id}': Operation<
    '/communications/calls/{call-id}/operations/{commsOperation-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/calls/{call-id}/operations': Operation<
    '/communications/calls/{call-id}/operations',
    'post'
  >;
}
