// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Play a prompt in the call. For more information about how to handle operations, see commsOperation
   */
  'POST /communications/calls/{call-id}/playPrompt': Operation<
    '/communications/calls/{call-id}/playPrompt',
    'post'
  >;
}
