// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Redirect an incoming call that hasn&#x27;t been answered or rejected yet. The terms &#x27;redirecting&#x27; and &#x27;forwarding&#x27; a call are used interchangeably. The bot is expected to redirect the call before the call times out. The current timeout value is 15 seconds.
   */
  'POST /communications/calls/{call-id}/redirect': Operation<
    '/communications/calls/{call-id}/redirect',
    'post'
  >;
}
