// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /communications/calls/{call-id}/sendDtmfTones': Operation<
    '/communications/calls/{call-id}/sendDtmfTones',
    'post'
  >;
}
