// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Subscribe to DTMF (dual-tone multi-frequency signaling) which allows you to be notified when the user presses keys on a &#x27;dialpad&#x27;.
   */
  'POST /communications/calls/{call-id}/subscribeToTone': Operation<
    '/communications/calls/{call-id}/subscribeToTone',
    'post'
  >;
}
