// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Transfer an active peer-to-peer call or group call. A consultative transfer means that the transferor can inform the person they want to transfer the call to (the transferee), before the transfer is made. This is opposed to transfering the call directly.
   */
  'POST /communications/calls/{call-id}/transfer': Operation<
    '/communications/calls/{call-id}/transfer',
    'post'
  >;
}
