// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Allow the application to unmute itself. This is a server unmute, meaning that the server will start sending audio packets for this participant to other participants again. For more information about how to handle unmute operations, see unmuteParticipantOperation.
   */
  'POST /communications/calls/{call-id}/unmute': Operation<
    '/communications/calls/{call-id}/unmute',
    'post'
  >;
}
