// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Update the application&#x27;s recording status associated with a call. This requires the use of the Teams policy-based recording solution.
   */
  'POST /communications/calls/{call-id}/updateRecordingStatus': Operation<
    '/communications/calls/{call-id}/updateRecordingStatus',
    'post'
  >;
}
