// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Activate a serviceApp.
   */
  'POST /solutions/backupRestore/serviceApps/{serviceApp-id}/activate': Operation<
    '/solutions/backupRestore/serviceApps/{serviceApp-id}/activate',
    'post'
  >;
}
