// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Deactivate a serviceApp.
   */
  'POST /solutions/backupRestore/serviceApps/{serviceApp-id}/deactivate': Operation<
    '/solutions/backupRestore/serviceApps/{serviceApp-id}/deactivate',
    'post'
  >;
}
