// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a serviceApp.
   */
  'DELETE /solutions/backupRestore/serviceApps/{serviceApp-id}': Operation<
    '/solutions/backupRestore/serviceApps/{serviceApp-id}',
    'delete'
  >;
  /**
   * Get a list of serviceApp objects and their properties.
   */
  'GET /solutions/backupRestore/serviceApps': Operation<
    '/solutions/backupRestore/serviceApps',
    'get'
  >;
  /**
   * Read the properties and relationships of a serviceApp object.
   */
  'GET /solutions/backupRestore/serviceApps/{serviceApp-id}': Operation<
    '/solutions/backupRestore/serviceApps/{serviceApp-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/serviceApps/{serviceApp-id}': Operation<
    '/solutions/backupRestore/serviceApps/{serviceApp-id}',
    'patch'
  >;
  /**
   * Create a new serviceApp.
   */
  'POST /solutions/backupRestore/serviceApps': Operation<
    '/solutions/backupRestore/serviceApps',
    'post'
  >;
}
