// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/primaryChannel/messages/{chatMessage-id}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}',
    'delete'
  >;
  /**
   * A collection of all the messages in the channel. A navigation property. Nullable.
   */
  'GET /teams/{team-id}/primaryChannel/messages': Operation<
    '/teams/{team-id}/primaryChannel/messages',
    'get'
  >;
  /**
   * A collection of all the messages in the channel. A navigation property. Nullable.
   */
  'GET /teams/{team-id}/primaryChannel/messages/{chatMessage-id}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/primaryChannel/messages/{chatMessage-id}': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/primaryChannel/messages': Operation<
    '/teams/{team-id}/primaryChannel/messages',
    'post'
  >;
}
