// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /teams/{team-id}/primaryChannel/messages/{chatMessage-id}/setReaction': Operation<
    '/teams/{team-id}/primaryChannel/messages/{chatMessage-id}/setReaction',
    'post'
  >;
}
