// DO NOT EDIT THIS FILE
import type { Operation } from "./common.d.ts";

export interface Endpoints {
  /**
   * Delete an application object. When deleted, apps are moved to a temporary container and can be restored within 30 days. After that time, they are permanently deleted.
   */
  "DELETE /applications(appId&#x3D;&#x27;{appId}&#x27;)": Operation<
    "/applications(appId&#x3D;&#x27;{appId}&#x27;)",
    "delete"
  >;
  /**
   * Get the properties and relationships of an application object.
   */
  "GET /applications(appId&#x3D;&#x27;{appId}&#x27;)": Operation<
    "/applications(appId&#x3D;&#x27;{appId}&#x27;)",
    "get"
  >;
  /**
   * Create a new application object if it doesn&#x27;t exist, or update the properties of an existing application object.
   */
  "PATCH /applications(appId&#x3D;&#x27;{appId}&#x27;)": Operation<
    "/applications(appId&#x3D;&#x27;{appId}&#x27;)",
    "patch"
  >;
}
