// DO NOT EDIT THIS FILE
import type { Operation } from './common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teamsTemplates/{teamsTemplate-id}': Operation<
    '/teamsTemplates/{teamsTemplate-id}',
    'delete'
  >;
  /**
   */
  'GET /teamsTemplates': Operation<'/teamsTemplates', 'get'>;
  /**
   */
  'GET /teamsTemplates/{teamsTemplate-id}': Operation<'/teamsTemplates/{teamsTemplate-id}', 'get'>;
  /**
   */
  'PATCH /teamsTemplates/{teamsTemplate-id}': Operation<
    '/teamsTemplates/{teamsTemplate-id}',
    'patch'
  >;
  /**
   */
  'POST /teamsTemplates': Operation<'/teamsTemplates', 'post'>;
}
