// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count": Operation<
    "/teamwork/deletedTeams/{deletedTeam-id}/channels/{channel-id}/messages/{chatMessage-id}/replies/$count",
    "get"
  >;
}
