// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /applications/{application-id}/owners/graph.servicePrincipal": Operation<
    "/applications/{application-id}/owners/graph.servicePrincipal",
    "get"
  >;
  /**
   */
  "GET /applications/{application-id}/owners/{directoryObject-id}/graph.servicePrincipal": Operation<
    "/applications/{application-id}/owners/{directoryObject-id}/graph.servicePrincipal",
    "get"
  >;
}
