// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Hide a chat for a user.
   */
  'POST /users/{user-id}/chats/{chat-id}/hideForUser': Operation<
    '/users/{user-id}/chats/{chat-id}/hideForUser',
    'post'
  >;
}
