// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/chats/{chat-id}': Operation<
    '/users/{user-id}/chats/{chat-id}',
    'delete'
  >;
  /**
   * Retrieve the list of chats that the user is part of. This method supports federation. When a user ID is provided, the calling application must belong to the same tenant that the user belongs to.
   */
  'GET /users/{user-id}/chats': Operation<'/users/{user-id}/chats', 'get'>;
  /**
   * Retrieve a single chat (without its messages). This method supports federation. To access a chat, at least one chat member must belong to the tenant the request initiated from.
   */
  'GET /users/{user-id}/chats/{chat-id}': Operation<'/users/{user-id}/chats/{chat-id}', 'get'>;
  /**
   */
  'PATCH /users/{user-id}/chats/{chat-id}': Operation<'/users/{user-id}/chats/{chat-id}', 'patch'>;
  /**
   */
  'POST /users/{user-id}/chats': Operation<'/users/{user-id}/chats', 'post'>;
}
