// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/chats/{chat-id}/lastMessagePreview': Operation<
    '/users/{user-id}/chats/{chat-id}/lastMessagePreview',
    'delete'
  >;
  /**
   * Preview of the last message sent in the chat. Null if no messages were sent in the chat. Currently, only the list chats operation supports this property.
   */
  'GET /users/{user-id}/chats/{chat-id}/lastMessagePreview': Operation<
    '/users/{user-id}/chats/{chat-id}/lastMessagePreview',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/chats/{chat-id}/lastMessagePreview': Operation<
    '/users/{user-id}/chats/{chat-id}/lastMessagePreview',
    'patch'
  >;
}
