// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'delete'
  >;
  /**
   * A collection of permissions granted to apps for the chat.
   */
  'GET /users/{user-id}/chats/{chat-id}/permissionGrants': Operation<
    '/users/{user-id}/chats/{chat-id}/permissionGrants',
    'get'
  >;
  /**
   * A collection of permissions granted to apps for the chat.
   */
  'GET /users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'get'
  >;
  /**
   */
  'PATCH /users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}': Operation<
    '/users/{user-id}/chats/{chat-id}/permissionGrants/{resourceSpecificPermissionGrant-id}',
    'patch'
  >;
  /**
   */
  'POST /users/{user-id}/chats/{chat-id}/permissionGrants': Operation<
    '/users/{user-id}/chats/{chat-id}/permissionGrants',
    'post'
  >;
}
