// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Unhide a chat for a user.
   */
  'POST /users/{user-id}/chats/{chat-id}/unhideForUser': Operation<
    '/users/{user-id}/chats/{chat-id}/unhideForUser',
    'post'
  >;
}
