// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendars/{calendar-id}/calendarPermissions/$count': Operation<
    '/me/calendars/{calendar-id}/calendarPermissions/$count',
    'get'
  >;
}
