// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /applications/{application-id}/owners/graph.user': Operation<
    '/applications/{application-id}/owners/graph.user',
    'get'
  >;
  /**
   */
  'GET /applications/{application-id}/owners/{directoryObject-id}/graph.user': Operation<
    '/applications/{application-id}/owners/{directoryObject-id}/graph.user',
    'get'
  >;
}
