// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /chats/{chat-id}/installedApps/$count": Operation<
    "/chats/{chat-id}/installedApps/$count",
    "get"
  >;
}
