// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Uninstall an app installed within a chat.
   */
  'DELETE /chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'delete'
  >;
  /**
   * List all app installations within a chat.
   */
  'GET /chats/{chat-id}/installedApps': Operation<'/chats/{chat-id}/installedApps', 'get'>;
  /**
   * Get an app installed in a chat.
   */
  'GET /chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'get'
  >;
  /**
   */
  'PATCH /chats/{chat-id}/installedApps/{teamsAppInstallation-id}': Operation<
    '/chats/{chat-id}/installedApps/{teamsAppInstallation-id}',
    'patch'
  >;
  /**
   * Install a teamsApp to the specified chat.
   */
  'POST /chats/{chat-id}/installedApps': Operation<'/chats/{chat-id}/installedApps', 'post'>;
}
