// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   * List all the functions currently supported in the attributeMappingSource.
   */
  "GET /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema/functions()": Operation<
    "/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema/functions()",
    "get"
  >;
}
