// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema',
    'delete'
  >;
  /**
   * The synchronization schema configured for the job.
   */
  'GET /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema',
    'get'
  >;
  /**
   */
  'PATCH /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema',
    'patch'
  >;
}
