// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Parse a given string expression into an attributeMappingSource object. For more information about expressions, see Writing Expressions for Attribute Mappings in Microsoft Entra ID.
   */
  'POST /applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema/parseExpression': Operation<
    '/applications/{application-id}/synchronization/jobs/{synchronizationJob-id}/schema/parseExpression',
    'post'
  >;
}
