// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The content stream, if the item represents a file.
   */
  'DELETE /teams/{team-id}/primaryChannel/filesFolder/content': Operation<
    '/teams/{team-id}/primaryChannel/filesFolder/content',
    'delete'
  >;
  /**
   * The content stream, if the item represents a file.
   */
  'GET /teams/{team-id}/primaryChannel/filesFolder/content': Operation<
    '/teams/{team-id}/primaryChannel/filesFolder/content',
    'get'
  >;
  /**
   * The content stream, if the item represents a file.
   */
  'PUT /teams/{team-id}/primaryChannel/filesFolder/content': Operation<
    '/teams/{team-id}/primaryChannel/filesFolder/content',
    'put'
  >;
}
