// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Metadata for the location where the channel&#x27;s files are stored.
   */
  'GET /teams/{team-id}/primaryChannel/filesFolder': Operation<
    '/teams/{team-id}/primaryChannel/filesFolder',
    'get'
  >;
}
