// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/directories/$count": Operation<
    "/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}/schema/directories/$count",
    "get"
  >;
}
