// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}',
    'delete'
  >;
  /**
   * The list of OneDrive for Business restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/oneDriveForBusinessRestoreSessions': Operation<
    '/solutions/backupRestore/oneDriveForBusinessRestoreSessions',
    'get'
  >;
  /**
   * The list of OneDrive for Business restore sessions available in the tenant.
   */
  'GET /solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}',
    'get'
  >;
  /**
   * Update the properties of a oneDriveForBusinessRestoreSession object.
   */
  'PATCH /solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}': Operation<
    '/solutions/backupRestore/oneDriveForBusinessRestoreSessions/{oneDriveForBusinessRestoreSession-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/oneDriveForBusinessRestoreSessions': Operation<
    '/solutions/backupRestore/oneDriveForBusinessRestoreSessions',
    'post'
  >;
}
