// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Invite participants to the active call. For more information about how to handle operations, see commsOperation.
   */
  'POST /communications/calls/{call-id}/participants/invite': Operation<
    '/communications/calls/{call-id}/participants/invite',
    'post'
  >;
}
