// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Mute a specific participant in the call. This is a server mute, meaning that the server will drop all audio packets for this participant, even if the participant continues to stream audio. For more information about how to handle mute operations, see muteParticipantOperation.
   */
  'POST /communications/calls/{call-id}/participants/{participant-id}/mute': Operation<
    '/communications/calls/{call-id}/participants/{participant-id}/mute',
    'post'
  >;
}
