// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Put a participant on hold and play music in the background.
   */
  'POST /communications/calls/{call-id}/participants/{participant-id}/startHoldMusic': Operation<
    '/communications/calls/{call-id}/participants/{participant-id}/startHoldMusic',
    'post'
  >;
}
