// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendarView/{event-id}/instances/{event-id1}/attachments/$count': Operation<
    '/me/calendarView/{event-id}/instances/{event-id1}/attachments/$count',
    'get'
  >;
}
