// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Deletes a user.
   */
  'DELETE /users/{user-id}': Operation<'/users/{user-id}', 'delete'>;
  /**
   * Retrieve a list of user objects.
   */
  'GET /users': Operation<'/users', 'get'>;
  /**
   * Read properties and relationships of the user object.
   */
  'GET /users/{user-id}': Operation<'/users/{user-id}', 'get'>;
  /**
   * Update the properties of a user object.
   */
  'PATCH /users/{user-id}': Operation<'/users/{user-id}', 'patch'>;
  /**
   * Create a new user.
The request body contains the user to create. At a minimum, you must specify the required properties for the user. You can optionally specify any other writable properties.
   */
  'POST /users': Operation<'/users', 'post'>;
}
