// DO NOT EDIT THIS FILE
import type { Operation } from './../common.d.ts';

export interface Endpoints {
  /**
   * Retrieve a list of user objects.
   */
  'GET /users': Operation<'/users', 'get'>;
  /**
   * Create a new user.
The request body contains the user to create. At a minimum, you must specify the required properties for the user. You can optionally specify any other writable properties.
   */
  'POST /users': Operation<'/users', 'post'>;
}
