// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count': Operation<
    '/me/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count',
    'get'
  >;
}
