// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Unshare a channel with a team by deleting the corresponding sharedWithChannelTeamInfo resource. This operation is allowed only for channels with a membershipType value of shared.
   */
  'DELETE /teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}',
    'delete'
  >;
  /**
   * Get the list of teams that has been shared a specified channel. This operation is allowed only for channels with a membershipType value of shared.
   */
  'GET /teams/{team-id}/channels/{channel-id}/sharedWithTeams': Operation<
    '/teams/{team-id}/channels/{channel-id}/sharedWithTeams',
    'get'
  >;
  /**
   * Get a team that has been shared with a specified channel. This operation is allowed only for channels with a membershipType value of shared.
   */
  'GET /teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/sharedWithTeams/{sharedWithChannelTeamInfo-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/channels/{channel-id}/sharedWithTeams': Operation<
    '/teams/{team-id}/channels/{channel-id}/sharedWithTeams',
    'post'
  >;
}
