// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/replies/{chatMessage-id1}/hostedContents/$count',
    'get'
  >;
}
