// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Removes (unpins) a tab from the specified channel within a team.
   */
  'DELETE /teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}',
    'delete'
  >;
  /**
   * Retrieve the list of tabs in the specified channel within a team.
   */
  'GET /teams/{team-id}/channels/{channel-id}/tabs': Operation<
    '/teams/{team-id}/channels/{channel-id}/tabs',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of the specified tab in a channel within a team.
   */
  'GET /teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}',
    'get'
  >;
  /**
   * Update the properties of the specified tab.
This API can be used to configure the content of the tab.
   */
  'PATCH /teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}',
    'patch'
  >;
  /**
   * Add (pin) a tab to the specified channel within a team. The app must be preinstalled in the team and have the configurableTabs property defined in the app manifest.
   */
  'POST /teams/{team-id}/channels/{channel-id}/tabs': Operation<
    '/teams/{team-id}/channels/{channel-id}/tabs',
    'post'
  >;
}
