// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   * The unique identifier for an entity. Read-only.
   */
  "DELETE /me/photos/{profilePhoto-id}/$value": Operation<
    "/me/photos/{profilePhoto-id}/$value",
    "delete"
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  "GET /me/photos/{profilePhoto-id}/$value": Operation<
    "/me/photos/{profilePhoto-id}/$value",
    "get"
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  "PUT /me/photos/{profilePhoto-id}/$value": Operation<
    "/me/photos/{profilePhoto-id}/$value",
    "put"
  >;
}
