// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /teams/{team-id}/channels/{channel-id}/messages/$count": Operation<
    "/teams/{team-id}/channels/{channel-id}/messages/$count",
    "get"
  >;
}
