// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /chats/{chat-id}/tabs/$count": Operation<
    "/chats/{chat-id}/tabs/$count",
    "get"
  >;
}
