// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Remove (unpin) a tab from the specified chat.
   */
  'DELETE /chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/chats/{chat-id}/tabs/{teamsTab-id}',
    'delete'
  >;
  /**
   * Retrieve the list of tabs in the specified chat.
   */
  'GET /chats/{chat-id}/tabs': Operation<'/chats/{chat-id}/tabs', 'get'>;
  /**
   * Retrieve the properties and relationships of the specified tab in a chat.
   */
  'GET /chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/chats/{chat-id}/tabs/{teamsTab-id}',
    'get'
  >;
  /**
   * Update the properties of the specified tab in a chat. 
This can be used to configure the content of the tab.
   */
  'PATCH /chats/{chat-id}/tabs/{teamsTab-id}': Operation<
    '/chats/{chat-id}/tabs/{teamsTab-id}',
    'patch'
  >;
  /**
   * Add (pin) a tab to the specified chat. 
The corresponding app must already be installed in the chat.
   */
  'POST /chats/{chat-id}/tabs': Operation<'/chats/{chat-id}/tabs', 'post'>;
}
