// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /employeeExperience/learningProviders/$count': Operation<
    '/employeeExperience/learningProviders/$count',
    'get'
  >;
}
