// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\common.d.ts";

export interface Endpoints {
  /**
   * Delete a learningProvider resource and remove its registration in Viva Learning for a tenant.
   */
  "DELETE /employeeExperience/learningProviders/{learningProvider-id}": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}",
    "delete"
  >;
  /**
   * Delete the specified learningContent resource that represents the metadata of the specified provider&#x27;s ingested content.
   */
  "DELETE /employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)",
    "delete"
  >;
  /**
   * Delete a learningCourseActivity object using the course activity ID of either an assignment or a self-initiated activity.
   */
  "DELETE /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)",
    "delete"
  >;
  /**
   * Get a list of the learningProvider resources registered in Viva Learning for a tenant.
   */
  "GET /employeeExperience/learningProviders": Operation<
    "/employeeExperience/learningProviders",
    "get"
  >;
  /**
   * Read the properties and relationships of a learningProvider object.
   */
  "GET /employeeExperience/learningProviders/{learningProvider-id}": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}",
    "get"
  >;
  /**
   * Get the specified learningContent resource which represents the metadata of the specified provider&#x27;s ingested content.
   */
  "GET /employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)",
    "get"
  >;
  /**
   */
  "GET /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)",
    "get"
  >;
  /**
   * Update the properties of a learningProvider object.
   */
  "PATCH /employeeExperience/learningProviders/{learningProvider-id}": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}",
    "patch"
  >;
  /**
   */
  "PATCH /employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningContents(externalId&#x3D;&#x27;{externalId}&#x27;)",
    "patch"
  >;
  /**
   * Update the properties of a learningCourseActivity object.
   */
  "PATCH /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)": Operation<
    "/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities(externalcourseActivityId&#x3D;&#x27;{externalcourseActivityId}&#x27;)",
    "patch"
  >;
  /**
   * Create a new learningProvider object and register it with Viva Learning using the specified display name and logos for different themes.
   */
  "POST /employeeExperience/learningProviders": Operation<
    "/employeeExperience/learningProviders",
    "post"
  >;
}
