// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a learningProvider resource and remove its registration in Viva Learning for a tenant.
   */
  'DELETE /employeeExperience/learningProviders/{learningProvider-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}',
    'delete'
  >;
  /**
   * Get a list of the learningProvider resources registered in Viva Learning for a tenant.
   */
  'GET /employeeExperience/learningProviders': Operation<
    '/employeeExperience/learningProviders',
    'get'
  >;
  /**
   * Read the properties and relationships of a learningProvider object.
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}',
    'get'
  >;
  /**
   * Update the properties of a learningProvider object.
   */
  'PATCH /employeeExperience/learningProviders/{learningProvider-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}',
    'patch'
  >;
  /**
   * Create a new learningProvider object and register it with Viva Learning using the specified display name and logos for different themes.
   */
  'POST /employeeExperience/learningProviders': Operation<
    '/employeeExperience/learningProviders',
    'post'
  >;
}
