// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete the specified learningContent resource that represents the metadata of the specified provider&#x27;s ingested content.
   */
  'DELETE /employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}',
    'delete'
  >;
  /**
   * Get a list of the learningContent resources and their properties. This list represents the metadata of the specified provider&#x27;s content in Viva Learning.
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}/learningContents': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents',
    'get'
  >;
  /**
   * Get the specified learningContent resource which represents the metadata of the specified provider&#x27;s ingested content.
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}',
    'get'
  >;
  /**
   */
  'PATCH /employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents/{learningContent-id}',
    'patch'
  >;
  /**
   */
  'POST /employeeExperience/learningProviders/{learningProvider-id}/learningContents': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningContents',
    'post'
  >;
}
