// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a learningCourseActivity object using the course activity ID of either an assignment or a self-initiated activity.
   */
  'DELETE /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}',
    'delete'
  >;
  /**
   * Get the specified learningCourseActivity object using either an ID or an externalCourseActivityId of the learning provider, or a courseActivityId of a user.
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities',
    'get'
  >;
  /**
   */
  'GET /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}',
    'get'
  >;
  /**
   * Update the properties of a learningCourseActivity object.
   */
  'PATCH /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities/{learningCourseActivity-id}',
    'patch'
  >;
  /**
   * Create a new learningCourseActivity object. A learning course activity can be one of two types: 
- Assignment
- Self-initiated Use this method to create either type of activity.
   */
  'POST /employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities': Operation<
    '/employeeExperience/learningProviders/{learningProvider-id}/learningCourseActivities',
    'post'
  >;
}
