// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}',
    'delete'
  >;
  /**
   * The events in the calendar. Navigation property. Read-only.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events',
    'get'
  >;
  /**
   * The events in the calendar. Navigation property. Read-only.
   */
  'GET /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}',
    'patch'
  >;
  /**
   */
  'POST /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events',
    'post'
  >;
}
