// DO NOT EDIT THIS FILE
import type { Operation } from "./../../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/onlineMeetings/{onlineMeeting-id}/recordings/$count": Operation<
    "/communications/onlineMeetings/{onlineMeeting-id}/recordings/$count",
    "get"
  >;
}
