// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/onlineMeetings/{onlineMeeting-id}/recordings/delta()": Operation<
    "/communications/onlineMeetings/{onlineMeeting-id}/recordings/delta()",
    "get"
  >;
}
