// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'delete'
  >;
  /**
   * The recordings of an online meeting. Read-only.
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}/recordings': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/recordings',
    'get'
  >;
  /**
   * The recordings of an online meeting. Read-only.
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/recordings/{callRecording-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/onlineMeetings/{onlineMeeting-id}/recordings': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/recordings',
    'post'
  >;
}
