// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Acquire an OAuth access token to authorize the Microsoft Entra provisioning service to provision users into an application.
   */
  'POST /applications/{application-id}/synchronization/acquireAccessToken': Operation<
    '/applications/{application-id}/synchronization/acquireAccessToken',
    'post'
  >;
}
