// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization': Operation<
    '/applications/{application-id}/synchronization',
    'delete'
  >;
  /**
   * Represents the capability for Microsoft Entra identity synchronization through the Microsoft Graph API.
   */
  'GET /applications/{application-id}/synchronization': Operation<
    '/applications/{application-id}/synchronization',
    'get'
  >;
  /**
   */
  'PUT /applications/{application-id}/synchronization': Operation<
    '/applications/{application-id}/synchronization',
    'put'
  >;
}
