// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'PUT /applications/{application-id}/synchronization/secrets': Operation<
    '/applications/{application-id}/synchronization/secrets',
    'put'
  >;
}
