// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}',
    'delete'
  >;
  /**
   * Preconfigured synchronization settings for a particular application.
   */
  'GET /applications/{application-id}/synchronization/templates': Operation<
    '/applications/{application-id}/synchronization/templates',
    'get'
  >;
  /**
   * Preconfigured synchronization settings for a particular application.
   */
  'GET /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}',
    'get'
  >;
  /**
   * Update (override) the synchronization template associated with a given application.
   */
  'PATCH /applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}': Operation<
    '/applications/{application-id}/synchronization/templates/{synchronizationTemplate-id}',
    'patch'
  >;
  /**
   */
  'POST /applications/{application-id}/synchronization/templates': Operation<
    '/applications/{application-id}/synchronization/templates',
    'post'
  >;
}
