// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   * Remove an owner from an application. As a recommended best practice, apps should have at least two owners.
   */
  'DELETE /applications/{application-id}/owners/$ref': Operation<
    '/applications/{application-id}/owners/$ref',
    'delete'
  >;
  /**
   * Remove an owner from an application. As a recommended best practice, apps should have at least two owners.
   */
  'DELETE /applications/{application-id}/owners/{directoryObject-id}/$ref': Operation<
    '/applications/{application-id}/owners/{directoryObject-id}/$ref',
    'delete'
  >;
  /**
   * Retrieve a list of owners for an application that are directoryObject types.
   */
  'GET /applications/{application-id}/owners/$ref': Operation<
    '/applications/{application-id}/owners/$ref',
    'get'
  >;
  /**
   * Add an owner to an application. Currently, only individual users are supported as owners of applications.
   */
  'POST /applications/{application-id}/owners/$ref': Operation<
    '/applications/{application-id}/owners/$ref',
    'post'
  >;
}
