// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   * The unique identifier for an entity. Read-only.
   */
  'DELETE /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value',
    'delete'
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  'GET /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value',
    'get'
  >;
  /**
   * The unique identifier for an entity. Read-only.
   */
  'PUT /users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value': Operation<
    '/users/{user-id}/chats/{chat-id}/messages/{chatMessage-id}/hostedContents/{chatMessageHostedContent-id}/$value',
    'put'
  >;
}
