// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}/transcripts/$count': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts/$count',
    'get'
  >;
}
