// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'delete'
  >;
  /**
   * The transcripts of an online meeting. Read-only.
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}/transcripts': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts',
    'get'
  >;
  /**
   * The transcripts of an online meeting. Read-only.
   */
  'GET /communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'get'
  >;
  /**
   */
  'PATCH /communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts/{callTranscript-id}',
    'patch'
  >;
  /**
   */
  'POST /communications/onlineMeetings/{onlineMeeting-id}/transcripts': Operation<
    '/communications/onlineMeetings/{onlineMeeting-id}/transcripts',
    'post'
  >;
}
