// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /teamwork/deletedChats/$count': Operation<'/teamwork/deletedChats/$count', 'get'>;
}
