// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teamwork/deletedChats/{deletedChat-id}': Operation<
    '/teamwork/deletedChats/{deletedChat-id}',
    'delete'
  >;
  /**
   * Read the properties and relationships of a deletedChat object.
   */
  'GET /teamwork/deletedChats': Operation<'/teamwork/deletedChats', 'get'>;
  /**
   * Read the properties and relationships of a deletedChat object.
   */
  'GET /teamwork/deletedChats/{deletedChat-id}': Operation<
    '/teamwork/deletedChats/{deletedChat-id}',
    'get'
  >;
  /**
   */
  'PATCH /teamwork/deletedChats/{deletedChat-id}': Operation<
    '/teamwork/deletedChats/{deletedChat-id}',
    'patch'
  >;
  /**
   */
  'POST /teamwork/deletedChats': Operation<'/teamwork/deletedChats', 'post'>;
}
