// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Restore a  deletedChat to an active chat.
   */
  'POST /teamwork/deletedChats/{deletedChat-id}/undoDelete': Operation<
    '/teamwork/deletedChats/{deletedChat-id}/undoDelete',
    'post'
  >;
}
