// DO NOT EDIT THIS FILE
import type { Operation } from "./../../common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /solutions/bookingCurrencies/$count": Operation<
    "/solutions/bookingCurrencies/$count",
    "get"
  >;
}
