// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.d.ts';

export interface Endpoints {
  /**
   */
  'GET /solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}/siteInclusionRules/$count': Operation<
    '/solutions/backupRestore/sharePointProtectionPolicies/{sharePointProtectionPolicy-id}/siteInclusionRules/$count',
    'get'
  >;
}
