// DO NOT EDIT THIS FILE
import type { Operation } from "./..\..\..\..\common.d.ts";

export interface Endpoints {
  /**
   */
  "GET /communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/$count": Operation<
    "/communications/callRecords/{callRecord-id}/sessions/{session-id}/segments/$count",
    "get"
  >;
}
