// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}': Operation<
    '/teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}',
    'delete'
  >;
  /**
   * Retrieve the properties and relationships of all offerShiftRequest objects in a team.
   */
  'GET /teams/{team-id}/schedule/offerShiftRequests': Operation<
    '/teams/{team-id}/schedule/offerShiftRequests',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of an offerShiftRequest object.
   */
  'GET /teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}': Operation<
    '/teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}': Operation<
    '/teams/{team-id}/schedule/offerShiftRequests/{offerShiftRequest-id}',
    'patch'
  >;
  /**
   * Create an instance of an offerShiftRequest.
   */
  'POST /teams/{team-id}/schedule/offerShiftRequests': Operation<
    '/teams/{team-id}/schedule/offerShiftRequests',
    'post'
  >;
}
