// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete an openShift object.
   */
  'DELETE /teams/{team-id}/schedule/openShifts/{openShift-id}': Operation<
    '/teams/{team-id}/schedule/openShifts/{openShift-id}',
    'delete'
  >;
  /**
   * List openShift objects in a team.
   */
  'GET /teams/{team-id}/schedule/openShifts': Operation<
    '/teams/{team-id}/schedule/openShifts',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of an openshift object.
   */
  'GET /teams/{team-id}/schedule/openShifts/{openShift-id}': Operation<
    '/teams/{team-id}/schedule/openShifts/{openShift-id}',
    'get'
  >;
  /**
   * Update the properties of an openShift object.
   */
  'PATCH /teams/{team-id}/schedule/openShifts/{openShift-id}': Operation<
    '/teams/{team-id}/schedule/openShifts/{openShift-id}',
    'patch'
  >;
  /**
   * Create an instance of an openShift object.
   */
  'POST /teams/{team-id}/schedule/openShifts': Operation<
    '/teams/{team-id}/schedule/openShifts',
    'post'
  >;
}
