// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Mark a schedulingGroup as inactive by setting its isActive property.
This method does not remove the schedulingGroup from the schedule. Existing shift instances assigned to the scheduling group remain part of the group.
   */
  'DELETE /teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}': Operation<
    '/teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}',
    'delete'
  >;
  /**
   * Get the list of schedulingGroups in this schedule.
   */
  'GET /teams/{team-id}/schedule/schedulingGroups': Operation<
    '/teams/{team-id}/schedule/schedulingGroups',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of a schedulingGroup by ID.
   */
  'GET /teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}': Operation<
    '/teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}',
    'get'
  >;
  /**
   * Replace an existing schedulingGroup. If the specified schedulingGroup doesn&#x27;t exist, this method returns 404 Not found.
   */
  'PATCH /teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}': Operation<
    '/teams/{team-id}/schedule/schedulingGroups/{schedulingGroup-id}',
    'patch'
  >;
  /**
   * Create a new schedulingGroup.
   */
  'POST /teams/{team-id}/schedule/schedulingGroups': Operation<
    '/teams/{team-id}/schedule/schedulingGroups',
    'post'
  >;
}
