// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a shift from the schedule.
   */
  'DELETE /teams/{team-id}/schedule/shifts/{shift-id}': Operation<
    '/teams/{team-id}/schedule/shifts/{shift-id}',
    'delete'
  >;
  /**
   * Get the list of shift instances in a schedule.
   */
  'GET /teams/{team-id}/schedule/shifts': Operation<'/teams/{team-id}/schedule/shifts', 'get'>;
  /**
   * Retrieve the properties and relationships of a shift object by ID.
   */
  'GET /teams/{team-id}/schedule/shifts/{shift-id}': Operation<
    '/teams/{team-id}/schedule/shifts/{shift-id}',
    'get'
  >;
  /**
   * Replace an existing shift. If the specified shift doesn&#x27;t exist, this method returns 404 Not found. The duration of a shift can&#x27;t be less than 1 minute or longer than 24 hours.
   */
  'PATCH /teams/{team-id}/schedule/shifts/{shift-id}': Operation<
    '/teams/{team-id}/schedule/shifts/{shift-id}',
    'patch'
  >;
  /**
   * Create a new shift instance in a schedule. The duration of a shift cannot be less than 1 minute or longer than 24 hours.
   */
  'POST /teams/{team-id}/schedule/shifts': Operation<'/teams/{team-id}/schedule/shifts', 'post'>;
}
