// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}': Operation<
    '/teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}',
    'delete'
  >;
  /**
   * Retrieve a list of swapShiftsChangeRequest objects in the team.
   */
  'GET /teams/{team-id}/schedule/swapShiftsChangeRequests': Operation<
    '/teams/{team-id}/schedule/swapShiftsChangeRequests',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of a swapShiftsChangeRequest object.
   */
  'GET /teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}': Operation<
    '/teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}': Operation<
    '/teams/{team-id}/schedule/swapShiftsChangeRequests/{swapShiftsChangeRequest-id}',
    'patch'
  >;
  /**
   * Create an instance of a swapShiftsChangeRequest object.
   */
  'POST /teams/{team-id}/schedule/swapShiftsChangeRequests': Operation<
    '/teams/{team-id}/schedule/swapShiftsChangeRequests',
    'post'
  >;
}
