// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a timeOff instance from a schedule.
   */
  'DELETE /teams/{team-id}/schedule/timesOff/{timeOff-id}': Operation<
    '/teams/{team-id}/schedule/timesOff/{timeOff-id}',
    'delete'
  >;
  /**
   * Get the list of timeOff instances in a schedule.
   */
  'GET /teams/{team-id}/schedule/timesOff': Operation<'/teams/{team-id}/schedule/timesOff', 'get'>;
  /**
   * Retrieve the properties and relationships of a timeOff object by ID.
   */
  'GET /teams/{team-id}/schedule/timesOff/{timeOff-id}': Operation<
    '/teams/{team-id}/schedule/timesOff/{timeOff-id}',
    'get'
  >;
  /**
   * Replace an existing timeOff object. If the specified timeOff object doesn&#x27;t exist, this method returns 404 Not found.
   */
  'PATCH /teams/{team-id}/schedule/timesOff/{timeOff-id}': Operation<
    '/teams/{team-id}/schedule/timesOff/{timeOff-id}',
    'patch'
  >;
  /**
   * Create a new timeOff instance in a schedule.
   */
  'POST /teams/{team-id}/schedule/timesOff': Operation<
    '/teams/{team-id}/schedule/timesOff',
    'post'
  >;
}
