// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Mark a timeOffReason as inactive by setting the isActive property. Every team must include at least one timeoff reason. This method doesn&#x27;t remove the specified timeOffReason instance. timeOffItem instances that have been assigned this reason remain assigned to this reason.
   */
  'DELETE /teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}': Operation<
    '/teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}',
    'delete'
  >;
  /**
   * Get the list of timeOffReasons in a schedule.
   */
  'GET /teams/{team-id}/schedule/timeOffReasons': Operation<
    '/teams/{team-id}/schedule/timeOffReasons',
    'get'
  >;
  /**
   * Retrieve the properties and relationships of a timeOffReason object by ID.
   */
  'GET /teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}': Operation<
    '/teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}',
    'get'
  >;
  /**
   * Replace an existing timeOffReason. If the specified timeOffReason doesn&#x27;t exist, this method returns 404 Not found.
   */
  'PATCH /teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}': Operation<
    '/teams/{team-id}/schedule/timeOffReasons/{timeOffReason-id}',
    'patch'
  >;
  /**
   * Create a new timeOffReason.
   */
  'POST /teams/{team-id}/schedule/timeOffReasons': Operation<
    '/teams/{team-id}/schedule/timeOffReasons',
    'post'
  >;
}
